import { PrismaClient } from '@prisma/client'
import bcrypt from 'bcryptjs'

const prisma = new PrismaClient()

async function main() {
  console.log('🌱 Starting Bareo Database Seeding...')

  // Clear existing records
  await prisma.review.deleteMany()
  await prisma.fAQ.deleteMany()
  await prisma.ingredient.deleteMany()
  await prisma.productImage.deleteMany()
  await prisma.cartItem.deleteMany()
  await prisma.cart.deleteMany()
  await prisma.orderItem.deleteMany()
  await prisma.orderTimeline.deleteMany()
  await prisma.order.deleteMany()
  await prisma.product.deleteMany()
  await prisma.category.deleteMany()
  await prisma.coupon.deleteMany()
  await prisma.offer.deleteMany()
  await prisma.paymentMethod.deleteMany()
  await prisma.address.deleteMany()
  await prisma.aiConsultation.deleteMany()
  await prisma.chatMessage.deleteMany()
  await prisma.user.deleteMany()

  // 1. Create Users
  const passwordHash = await bcrypt.hash('user123', 10)
  const adminPasswordHash = await bcrypt.hash('admin123', 10)
  const adminBareoPasswordHash = await bcrypt.hash('admin1234', 10)

  const admin = await prisma.user.create({
    data: {
      name: 'Dr. Sarah Jenkins',
      email: 'admin@bareo.com',
      password: adminPasswordHash,
      phone: '+91 98765 43210',
      role: 'ADMIN',
      avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=300&auto=format&fit=crop&q=80',
      gender: 'female',
      skinType: 'normal',
    },
  })

  const adminBareo = await prisma.user.create({
    data: {
      name: 'Bareo Admin System',
      email: 'admin@luminaskin.com',
      password: adminBareoPasswordHash,
      phone: '+91 90000 00000',
      role: 'ADMIN',
      avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=300&auto=format&fit=crop&q=80',
      gender: 'female',
      skinType: 'normal',
    },
  })

  const user = await prisma.user.create({
    data: {
      name: 'Ananya Sharma',
      email: 'user@luminaskin.com',
      password: passwordHash,
      phone: '+91 91234 56789',
      role: 'USER',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=300&auto=format&fit=crop&q=80',
      gender: 'female',
      skinType: 'combination',
    },
  })

  console.log(`👤 Created Users: ${admin.email} (Admin), ${adminBareo.email} (Admin), ${user.email} (User)`)

  // User Default Address
  await prisma.address.create({
    data: {
      userId: user.id,
      fullName: 'Ananya Sharma',
      phone: '+91 91234 56789',
      email: 'user@luminaskin.com',
      line1: 'Flat 402, Green Glen Layout',
      line2: 'Outer Ring Road, Bellandur',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560103',
      landmark: 'Near Central Mall',
      isDefault: true,
      label: 'home',
    },
  })

  // 2. Create Categories (4 Bareo Core Categories with valid Mongo ObjectIds)
  const catSkincare = await prisma.category.create({
    data: {
      name: 'Skincare',
      slug: 'skincare',
      image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=500&auto=format&fit=crop&q=80',
      description: 'Clean, dermatologically formulated skincare products engineered for skin barrier repair and glow.',
    },
  })

  const catHaircare = await prisma.category.create({
    data: {
      name: 'Hair Care',
      slug: 'hair-care',
      image: 'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=500&auto=format&fit=crop&q=80',
      description: 'Scalp-first hair care solutions infused with botanicals and active proteins for hair vitality.',
    },
  })

  const catBodycare = await prisma.category.create({
    data: {
      name: 'Body Care',
      slug: 'body-care',
      image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=500&auto=format&fit=crop&q=80',
      description: 'Nourishing body washes, scrubs, and lotions that restore skin elasticity and deep moisture.',
    },
  })

  const catBabycare = await prisma.category.create({
    data: {
      name: 'Baby Care',
      slug: 'baby-care',
      image: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?w=500&auto=format&fit=crop&q=80',
      description: 'Hypoallergenic, ultra-gentle formulas designed for delicate baby skin and scalp.',
    },
  })

  console.log(`📦 Created 4 Categories for Bareo`)

  // 3. Create Products (28 Bareo Products)
  const productsData = [
    // --- CATEGORY 1: SKYNCare (8 PRODUCTS) ---
    {
      slug: 'bareo-cica-niacinamide-calming-serum',
      name: 'Bareo Cica & Niacinamide Calming Serum',
      brand: 'Bareo',
      sku: 'BAR-SK-001',
      categoryId: catSkincare.id,
      categoryName: catSkincare.name,
      categorySlug: catSkincare.slug,
      shortDescription: 'Soothing barrier serum with 10% Niacinamide & 5% Centella',
      description: 'Bareo Cica & Niacinamide Calming Serum repairs damaged skin barriers, reduces redness, and balances oil production with pure botanical actives.',
      mrp: 699,
      offerPrice: 599,
      discount: 14,
      rating: 4.9,
      ratingCount: 184,
      stock: 95,
      isBestSeller: true,
      isTrending: true,
      isDoctorRecommended: true,
      isNew: false,
      isAiRecommended: true,
      skinTypes: JSON.stringify(['sensitive', 'oily', 'combination', 'dry', 'normal']),
      concerns: JSON.stringify(['redness', 'acne', 'sensitivity']),
      benefits: JSON.stringify(['Calms redness and inflammation instantly', 'Strengthens moisture barrier', 'Tightens enlarged pores', 'Lightweight non-sticky finish']),
      usage: JSON.stringify(['Apply 3-4 drops onto clean face.', 'Gently pat until absorbed.', 'Follow with Bareo hydrator.', 'Use AM and PM daily.']),
      keyFacts: JSON.stringify(['Dermatologically Tested', 'Fragrance-Free', '100% Vegan & Cruelty Free', 'pH 5.5 Balanced']),
      tags: JSON.stringify(['best-seller', 'niacinamide', 'cica', 'barrier-repair']),
      soldCount: 1420,
      status: 'active',
      images: ['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&auto=format&fit=crop&q=80'],
      ingredients: [
        { name: 'Niacinamide', description: 'Visibly reduces pore size and regulates oil', concentration: '10%' },
        { name: 'Centella Asiatica (Cica)', description: 'Soothes irritation and promotes skin healing', concentration: '5%' },
        { name: 'Hyaluronic Acid', description: 'Deeply hydrates multiple layers of the skin' },
      ],
      faqs: [
        { question: 'Can I use this with Vitamin C?', answer: 'Yes, our stabilized Niacinamide formula pairs safely with Vitamin C.' },
        { question: 'Is this suitable for rosacea-prone skin?', answer: 'Yes, Centella Asiatica helps soothe flushing and redness.' },
      ],
    },
    {
      slug: 'bareo-dewy-barrier-hyaluronic-hydrator',
      name: 'Bareo Dewy Barrier Hyaluronic Hydrator',
      brand: 'Bareo',
      sku: 'BAR-SK-002',
      categoryId: catSkincare.id,
      categoryName: catSkincare.name,
      categorySlug: catSkincare.slug,
      shortDescription: 'Multi-molecular hydration gel cream with Squalane & Ceramides',
      description: 'Quench thirsty skin with Bareo Dewy Barrier Hydrator. Infused with 5 molecular weights of Hyaluronic Acid and Plant Squalane for 72-hour moisture retention.',
      mrp: 599,
      offerPrice: 499,
      discount: 16,
      rating: 4.8,
      ratingCount: 156,
      stock: 110,
      isBestSeller: true,
      isTrending: true,
      isDoctorRecommended: true,
      isNew: false,
      isAiRecommended: true,
      skinTypes: JSON.stringify(['dry', 'normal', 'sensitive', 'combination']),
      concerns: JSON.stringify(['dryness', 'dehydration', 'dullness']),
      benefits: JSON.stringify(['Delivers 72 hours of uninterrupted hydration', 'Locks moisture with Squalane', 'Smooths fine dehydration lines', 'Dewy non-greasy glow']),
      usage: JSON.stringify(['Take a pea-sized amount.', 'Smooth evenly over face and neck.', 'Massage gently in upward motions.']),
      keyFacts: JSON.stringify(['Oil-Free Gel Formula', 'Non-Comedogenic', 'Cruelty Free']),
      tags: JSON.stringify(['hyaluronic-acid', 'squalane', 'moisturizer']),
      soldCount: 980,
      status: 'active',
      images: ['https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=800&auto=format&fit=crop&q=80'],
      ingredients: [
        { name: 'Multi-Molecular Hyaluronic Acid', description: 'Attracts 1000x its weight in water' },
        { name: 'Plant Squalane', description: 'Prevents transepidermal moisture loss' },
        { name: 'Ceramide NP', description: 'Restores outer barrier lipids' },
      ],
      faqs: [
        { question: 'Is this suitable under makeup?', answer: 'Yes! It acts as a smooth, hydrating base for foundation.' },
      ],
    },
    {
      slug: 'bareo-rice-water-alpha-arbutin-essence',
      name: 'Bareo Rice Water & Alpha Arbutin Essence',
      brand: 'Bareo',
      sku: 'BAR-SK-003',
      categoryId: catSkincare.id,
      categoryName: catSkincare.name,
      categorySlug: catSkincare.slug,
      shortDescription: 'Illuminating toner essence with 70% Fermented Rice Water & 2% Alpha Arbutin',
      description: 'Bareo Brightening Essence combines traditional Asian rice ferment technology with modern Alpha Arbutin to fade sun spots and restore natural radiance.',
      mrp: 749,
      offerPrice: 649,
      discount: 13,
      rating: 4.7,
      ratingCount: 112,
      stock: 80,
      isBestSeller: false,
      isTrending: true,
      isDoctorRecommended: false,
      isNew: true,
      isAiRecommended: true,
      skinTypes: JSON.stringify(['normal', 'combination', 'dry', 'oily']),
      concerns: JSON.stringify(['pigmentation', 'dullness', 'uneven-skin-tone']),
      benefits: JSON.stringify(['Fades dark marks and hyperpigmentation', 'Refines skin texture', 'Provides glass-skin luminosity']),
      usage: JSON.stringify(['Pour 4-5 drops into palms.', 'Press gently onto face until fully absorbed.']),
      keyFacts: JSON.stringify(['Alcohol-Free', 'Fermented Bio-Actives', 'Dermatologist Tested']),
      tags: JSON.stringify(['rice-water', 'alpha-arbutin', 'glow']),
      soldCount: 650,
      status: 'active',
      images: ['https://images.unsplash.com/photo-1608248597262-8381696f8c7e?w=800&auto=format&fit=crop&q=80'],
      ingredients: [
        { name: 'Fermented Rice Water', description: 'Rich in amino acids and antioxidants', concentration: '70%' },
        { name: 'Alpha Arbutin', description: 'Safely inhibits melanin synthesis', concentration: '2%' },
      ],
      faqs: [{ question: 'How long until I see results?', answer: 'Noticeable brightening is typically observed in 3-4 weeks.' }],
    },
    {
      slug: 'bareo-salicylic-acid-tea-tree-cleanser',
      name: 'Bareo Salicylic Acid & Tea Tree Cleanser',
      brand: 'Bareo',
      sku: 'BAR-SK-004',
      categoryId: catSkincare.id,
      categoryName: catSkincare.name,
      categorySlug: catSkincare.slug,
      shortDescription: 'Deep pore clarifying wash with 2% BHA & Australian Tea Tree',
      description: 'Dissolve stubborn blackheads, unclog pores, and calm active acne with Bareo Salicylic Acid Cleanser. Sulphate-free pH 5.5 formula.',
      mrp: 449,
      offerPrice: 399,
      discount: 11,
      rating: 4.8,
      ratingCount: 230,
      stock: 140,
      isBestSeller: true,
      isTrending: false,
      isDoctorRecommended: true,
      isNew: false,
      isAiRecommended: true,
      skinTypes: JSON.stringify(['oily', 'combination']),
      concerns: JSON.stringify(['acne', 'oiliness', 'blackheads']),
      benefits: JSON.stringify(['Unclogs hair follicles and pores', 'Controls excessive oil production for 8+ hours', 'Soothes active breakouts']),
      usage: JSON.stringify(['Lather 1 pump on wet face for 60 seconds.', 'Rinse thoroughly with warm water.']),
      keyFacts: JSON.stringify(['Sulphate-Free', 'Paraben-Free', 'Non-Drying']),
      tags: JSON.stringify(['salicylic-acid', 'cleanser', 'acne']),
      soldCount: 2100,
      status: 'active',
      images: ['https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&auto=format&fit=crop&q=80'],
      ingredients: [
        { name: 'Salicylic Acid (BHA)', description: 'Oil-soluble exfoliant for deep pore cleaning', concentration: '2%' },
        { name: 'Tea Tree Oil', description: 'Antibacterial botanical extract', concentration: '1%' },
      ],
      faqs: [{ question: 'Can I use this daily?', answer: 'Yes, formulated at skin-friendly pH 5.5 for daily morning and evening cleansing.' }],
    },
    {
      slug: 'bareo-invisible-shield-fluid-sunscreen-spf50',
      name: 'Bareo Invisible Shield Fluid Sunscreen SPF 50 PA++++',
      brand: 'Bareo',
      sku: 'BAR-SK-005',
      categoryId: catSkincare.id,
      categoryName: catSkincare.name,
      categorySlug: catSkincare.slug,
      shortDescription: 'Ultra-lightweight fluid sunscreen with Zero White Cast',
      description: 'Bareo Invisible Shield SPF 50 provides high-performance UVA/UVB protection with an airy, invisible matte finish. Infused with Vitamin E and Ceramides.',
      mrp: 649,
      offerPrice: 549,
      discount: 15,
      rating: 4.9,
      ratingCount: 310,
      stock: 150,
      isBestSeller: true,
      isTrending: true,
      isDoctorRecommended: true,
      isNew: false,
      isAiRecommended: true,
      skinTypes: JSON.stringify(['oily', 'combination', 'dry', 'normal', 'sensitive']),
      concerns: JSON.stringify(['sun-protection', 'aging', 'pigmentation']),
      benefits: JSON.stringify(['Broad-spectrum SPF 50 PA++++ protection', '100% Zero white cast', 'Water and sweat resistant', 'No eye sting']),
      usage: JSON.stringify(['Apply 2 fingers length on face and neck 15 mins before sun exposure.', 'Reapply every 2-3 hours.']),
      keyFacts: JSON.stringify(['Reef-Safe Filters', 'Dermatologist Approved', 'Non-Greasy']),
      tags: JSON.stringify(['sunscreen', 'spf50', 'best-seller']),
      soldCount: 3400,
      status: 'active',
      images: ['https://images.unsplash.com/photo-1567928256057-0a4f5b3513a9?w=800&auto=format&fit=crop&q=80'],
      ingredients: [
        { name: 'Broad Spectrum UV Complex', description: 'Modern photostable UV filters' },
        { name: 'Vitamin E', description: 'Neutralizes free radical damage' },
      ],
      faqs: [{ question: 'Does it leave a greasy film?', answer: 'No, it absorbs instantly into a velvety matte texture.' }],
    },
    {
      slug: 'bareo-peptide-repair-night-cream',
      name: 'Bareo Peptide Repair & Renewal Night Cream',
      brand: 'Bareo',
      sku: 'BAR-SK-006',
      categoryId: catSkincare.id,
      categoryName: catSkincare.name,
      categorySlug: catSkincare.slug,
      shortDescription: 'Nightly collagen boost cream with 5-Peptide Complex & Squalane',
      description: 'Awaken to plump, firm skin with Bareo Peptide Repair Cream. Works overnight to stimulate natural collagen, rebuild skin density, and smooth fine lines.',
      mrp: 899,
      offerPrice: 749,
      discount: 16,
      rating: 4.8,
      ratingCount: 88,
      stock: 65,
      isBestSeller: false,
      isTrending: true,
      isDoctorRecommended: true,
      isNew: false,
      isAiRecommended: true,
      skinTypes: JSON.stringify(['dry', 'normal', 'combination']),
      concerns: JSON.stringify(['aging', 'fine-lines', 'loss-of-firmness']),
      benefits: JSON.stringify(['Boosts skin elasticity overnight', 'Smooths appearance of fine lines', 'Deeply restores moisture barrier']),
      usage: JSON.stringify(['Apply a generous layer every night on clean face and neck.']),
      keyFacts: JSON.stringify(['Clinical Bio-Peptides', 'Cruelty Free', 'Dermatologically Tested']),
      tags: JSON.stringify(['night-cream', 'peptides', 'anti-aging']),
      soldCount: 520,
      status: 'active',
      images: ['https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=800&auto=format&fit=crop&q=80'],
      ingredients: [
        { name: '5-Peptide Complex', description: 'Signals skin to produce collagen and elastin' },
        { name: 'Shea Butter', description: 'Nourishes deep dermal layers' },
      ],
      faqs: [{ question: 'At what age should I start using peptides?', answer: 'Peptides are beneficial starting in your mid-20s for preventative care.' }],
    },
    {
      slug: 'bareo-clarifying-aha-bha-exfoliating-peel',
      name: 'Bareo Clarifying AHA + BHA Exfoliating Peel',
      brand: 'Bareo',
      sku: 'BAR-SK-007',
      categoryId: catSkincare.id,
      categoryName: catSkincare.name,
      categorySlug: catSkincare.slug,
      shortDescription: '10-minute rinse-off peeling wash with 10% Glycolic Acid & 2% Salicylic Acid',
      description: 'Transform rough, dull skin in 10 minutes with Bareo Exfoliating Peel. Removes dead surface cells and clears congested pores for instant baby-smooth skin.',
      mrp: 699,
      offerPrice: 599,
      discount: 14,
      rating: 4.7,
      ratingCount: 94,
      stock: 75,
      isBestSeller: false,
      isTrending: false,
      isDoctorRecommended: true,
      isNew: true,
      isAiRecommended: false,
      skinTypes: JSON.stringify(['oily', 'combination', 'normal']),
      concerns: JSON.stringify(['dullness', 'uneven-texture', 'blackheads']),
      benefits: JSON.stringify(['Instant smoothing of rough texture', 'Fades dull dead skin layer', 'Unclogs congested pores']),
      usage: JSON.stringify(['Apply evenly on dry face. Leave for MAX 10 minutes.', 'Rinse thoroughly with cold water. Use 1-2 times weekly.']),
      keyFacts: JSON.stringify(['Use SPF next morning', 'Rinse-Off Formula', 'Cruelty Free']),
      tags: JSON.stringify(['exfoliant', 'aha-bha', 'peel']),
      soldCount: 410,
      status: 'active',
      images: ['https://images.unsplash.com/photo-1567928256057-0a4f5b3513a9?w=800&auto=format&fit=crop&q=80'],
      ingredients: [
        { name: 'Glycolic Acid (AHA)', description: 'Exfoliates surface dead cells', concentration: '10%' },
        { name: 'Salicylic Acid (BHA)', description: 'Clears inner pore walls', concentration: '2%' },
      ],
      faqs: [{ question: 'Will my skin peel visibly?', answer: 'Micro-exfoliation occurs at a cellular level; no harsh flaking expected.' }],
    },
    {
      slug: 'bareo-squalane-vitamin-c-glow-face-oil',
      name: 'Bareo Squalane & Vitamin C Glow Face Oil',
      brand: 'Bareo',
      sku: 'BAR-SK-008',
      categoryId: catSkincare.id,
      categoryName: catSkincare.name,
      categorySlug: catSkincare.slug,
      shortDescription: 'Non-comedogenic radiance oil with 15% Vitamin C & Plant Squalane',
      description: 'Bareo Glow Face Oil locks in hydration while delivering a concentrated dose of stable 15% Vitamin C for an instant golden-hour radiance.',
      mrp: 849,
      offerPrice: 699,
      discount: 17,
      rating: 4.9,
      ratingCount: 140,
      stock: 60,
      isBestSeller: true,
      isTrending: true,
      isDoctorRecommended: false,
      isNew: false,
      isAiRecommended: true,
      skinTypes: JSON.stringify(['dry', 'normal', 'combination']),
      concerns: JSON.stringify(['dullness', 'dryness', 'pigmentation']),
      benefits: JSON.stringify(['Instant luminous glow', 'Fades hyperpigmentation marks', 'Non-comedogenic pore-safe oil']),
      usage: JSON.stringify(['Warm 2 drops between palms.', 'Press into face as final skincare step.']),
      keyFacts: JSON.stringify(['100% Plant Derived Squalane', 'Non-Greasy', 'Vegan']),
      tags: JSON.stringify(['face-oil', 'vitamin-c', 'squalane']),
      soldCount: 890,
      status: 'active',
      images: ['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&auto=format&fit=crop&q=80'],
      ingredients: [
        { name: 'Ethyl Ascorbic Acid (Vitamin C)', description: 'Highly stable brightening derivative', concentration: '15%' },
        { name: 'Sugarcane Squalane', description: 'Ultra-lightweight oil base' },
      ],
      faqs: [{ question: 'Will this cause breakouts?', answer: 'No, Squalane mimics natural skin sebum and is non-comedogenic.' }],
    },

    // --- CATEGORY 2: HAIR CARE (7 PRODUCTS) ---
    {
      slug: 'bareo-rosemary-biotin-scalp-shampoo',
      name: 'Bareo Rosemary & Biotin Scalp Revitalizing Shampoo',
      brand: 'Bareo',
      sku: 'BAR-HC-001',
      categoryId: catHaircare.id,
      categoryName: catHaircare.name,
      categorySlug: catHaircare.slug,
      shortDescription: 'Sulphate-free scalp stimulating shampoo with Rosemary Oil & Biotin',
      description: 'Strengthen hair follicles and reduce hair fall with Bareo Rosemary & Biotin Shampoo. Gently cleanses scalp buildup while stimulating micro-circulation.',
      mrp: 549,
      offerPrice: 449,
      discount: 18,
      rating: 4.8,
      ratingCount: 260,
      stock: 120,
      isBestSeller: true,
      isTrending: true,
      isDoctorRecommended: true,
      isNew: false,
      isAiRecommended: true,
      skinTypes: JSON.stringify(['all']),
      concerns: JSON.stringify(['hair-fall', 'scalp-care', 'thinning']),
      benefits: JSON.stringify(['Reduces hair fall up to 85%', 'Stimulates new hair growth', 'Sulphate-free gentle scalp wash']),
      usage: JSON.stringify(['Massage 2 pumps onto wet scalp for 2 minutes.', 'Rinse thoroughly. Follow with Bareo conditioner.']),
      keyFacts: JSON.stringify(['Sulphate & Paraben Free', 'Color-Safe', '100% Organic Rosemary']),
      tags: JSON.stringify(['shampoo', 'rosemary', 'hair-fall']),
      soldCount: 2800,
      status: 'active',
      images: ['https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=800&auto=format&fit=crop&q=80'],
      ingredients: [
        { name: 'Rosemary Essential Oil', description: 'Stimulates blood flow to roots' },
        { name: 'Biotin (Vitamin B7)', description: 'Strengthens hair shaft elasticity' },
      ],
      faqs: [{ question: 'Is this safe for color-treated hair?', answer: 'Yes, it is 100% sulphate-free and color-safe.' }],
    },
    {
      slug: 'bareo-argan-silk-peptide-conditioner',
      name: 'Bareo Argan Oil & Silk Peptide Hydrating Conditioner',
      brand: 'Bareo',
      sku: 'BAR-HC-002',
      categoryId: catHaircare.id,
      categoryName: catHaircare.name,
      categorySlug: catHaircare.slug,
      shortDescription: 'Deep moisturizing conditioner with Pure Moroccan Argan Oil',
      description: 'Bareo Argan Oil Conditioner smooths dry frizz, detangles knots, and restores silky shine to damaged hair strands.',
      mrp: 599,
      offerPrice: 499,
      discount: 16,
      rating: 4.7,
      ratingCount: 175,
      stock: 100,
      isBestSeller: false,
      isTrending: true,
      isDoctorRecommended: false,
      isNew: false,
      isAiRecommended: true,
      skinTypes: JSON.stringify(['all']),
      concerns: JSON.stringify(['frizz', 'dryness', 'damage']),
      benefits: JSON.stringify(['Instantly detangles and smooths frizz', 'Seals moisture into hair cuticle', 'Adds healthy silky gloss']),
      usage: JSON.stringify(['Apply to hair lengths after shampooing.', 'Leave for 3 minutes. Rinse with cold water.']),
      keyFacts: JSON.stringify(['Silicone-Free', 'Cruelty Free']),
      tags: JSON.stringify(['conditioner', 'argan-oil', 'frizz-control']),
      soldCount: 1450,
      status: 'active',
      images: ['https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=800&auto=format&fit=crop&q=80'],
      ingredients: [
        { name: 'Moroccan Argan Oil', description: 'Rich in fatty acids and Vitamin E' },
        { name: 'Silk Amino Acids', description: 'Repairs split cuticles' },
      ],
      faqs: [{ question: 'Should I apply this on scalp?', answer: 'Apply from mid-lengths to ends to avoid weighing down roots.' }],
    },
    {
      slug: 'bareo-rosemary-root-nourishing-hair-oil',
      name: 'Bareo Rosemary Root Nourishing Hair Oil',
      brand: 'Bareo',
      sku: 'BAR-HC-003',
      categoryId: catHaircare.id,
      categoryName: catHaircare.name,
      categorySlug: catHaircare.slug,
      shortDescription: 'Cold-pressed scalp oil with Rosemary, Bhringraj & Amla',
      description: 'Bareo Rosemary Root Oil is a traditional Ayurvedic blend enhanced with cold-pressed Rosemary to nourish hair follicles and boost density.',
      mrp: 499,
      offerPrice: 399,
      discount: 20,
      rating: 4.9,
      ratingCount: 290,
      stock: 130,
      isBestSeller: true,
      isTrending: true,
      isDoctorRecommended: true,
      isNew: false,
      isAiRecommended: true,
      skinTypes: JSON.stringify(['all']),
      concerns: JSON.stringify(['hair-fall', 'thinning', 'dry-scalp']),
      benefits: JSON.stringify(['Promotes thicker, fuller hair growth', 'Prevents dry scalp dandruff', 'Nourishes roots deeply']),
      usage: JSON.stringify(['Apply directly on scalp using applicator.', 'Massage gently. Leave for 1 hour or overnight before wash.']),
      keyFacts: JSON.stringify(['100% Pure Cold Pressed', 'No Mineral Oil', 'No Synthetic Fragrance']),
      tags: JSON.stringify(['hair-oil', 'rosemary', 'best-seller']),
      soldCount: 3100,
      status: 'active',
      images: ['https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=800&auto=format&fit=crop&q=80'],
      ingredients: [
        { name: 'Rosemary Oil', description: 'Proven botanical for scalp stimulation' },
        { name: 'Bhringraj Extract', description: 'Ancient herb for hair longevity' },
      ],
      faqs: [{ question: 'How often should I oil my hair?', answer: '2 to 3 times weekly before washing.' }],
    },
    {
      slug: 'bareo-scalp-balance-exfoliating-scrub',
      name: 'Bareo Scalp Balance Exfoliating Scrub',
      brand: 'Bareo',
      sku: 'BAR-HC-004',
      categoryId: catHaircare.id,
      categoryName: catHaircare.name,
      categorySlug: catHaircare.slug,
      shortDescription: 'Clarifying sea salt scrub for scalp detox & dandruff control',
      description: 'Bareo Scalp Balance Scrub gently buffs away dead skin flakes, product buildup, and excess oil for a squeaky clean, refreshed scalp environment.',
      mrp: 649,
      offerPrice: 549,
      discount: 15,
      rating: 4.7,
      ratingCount: 82,
      stock: 70,
      isBestSeller: false,
      isTrending: true,
      isDoctorRecommended: false,
      isNew: true,
      isAiRecommended: false,
      skinTypes: JSON.stringify(['all']),
      concerns: JSON.stringify(['dandruff', 'scalp-care', 'oiliness']),
      benefits: JSON.stringify(['Removes 99% of scalp product buildup', 'Soothes scalp itchiness', 'Promotes healthy root breathing']),
      usage: JSON.stringify(['Section wet hair.', 'Massage scrub into scalp in circular motions.', 'Rinse thoroughly and follow with shampoo.']),
      keyFacts: JSON.stringify(['Biodegradable Scrub Crystals', 'Tea Tree Infused']),
      tags: JSON.stringify(['scalp-scrub', 'dandruff', 'detox']),
      soldCount: 480,
      status: 'active',
      images: ['https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=800&auto=format&fit=crop&q=80'],
      ingredients: [
        { name: 'Micro Sea Salt', description: 'Exfoliates dead scalp cells' },
        { name: 'Peppermint Oil', description: 'Cools and revitalizes scalp' },
      ],
      faqs: [{ question: 'Will sea salt dry out my hair?', answer: 'No, it is blended with hydrating botanical oils.' }],
    },
    {
      slug: 'bareo-keratin-intense-repair-mask',
      name: 'Bareo Keratin Intense Repair Hair Mask',
      brand: 'Bareo',
      sku: 'BAR-HC-005',
      categoryId: catHaircare.id,
      categoryName: catHaircare.name,
      categorySlug: catHaircare.slug,
      shortDescription: 'Deep conditioning treatment mask with Plant Keratin & Macadamia',
      description: 'Restore strength to over-processed, heat-damaged hair with Bareo Keratin Repair Mask. Rebuilds protein bonds and stops breakage.',
      mrp: 749,
      offerPrice: 629,
      discount: 16,
      rating: 4.8,
      ratingCount: 104,
      stock: 60,
      isBestSeller: false,
      isTrending: false,
      isDoctorRecommended: true,
      isNew: false,
      isAiRecommended: true,
      skinTypes: JSON.stringify(['all']),
      concerns: JSON.stringify(['damage', 'breakage', 'split-ends']),
      benefits: JSON.stringify(['Reduces hair breakage by 90%', 'Restores protein moisture balance', 'Intense smooth finish']),
      usage: JSON.stringify(['Apply generously to damp hair.', 'Leave for 10-15 minutes.', 'Rinse thoroughly. Use once weekly.']),
      keyFacts: JSON.stringify(['Plant-Derived Keratin', 'Heat Damage Repair']),
      tags: JSON.stringify(['hair-mask', 'keratin', 'repair']),
      soldCount: 610,
      status: 'active',
      images: ['https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=800&auto=format&fit=crop&q=80'],
      ingredients: [
        { name: 'Hydrolyzed Plant Keratin', description: 'Fills structural cracks in hair fibers' },
        { name: 'Macadamia Nut Oil', description: 'Deeply conditions hair shaft' },
      ],
      faqs: [{ question: 'Can I use this after keratin treatment?', answer: 'Yes, it prolongs salon keratin treatment longevity.' }],
    },
    {
      slug: 'bareo-anti-frizz-gloss-leave-in-serum',
      name: 'Bareo Anti-Frizz Gloss Leave-In Hair Serum',
      brand: 'Bareo',
      sku: 'BAR-HC-006',
      categoryId: catHaircare.id,
      categoryName: catHaircare.name,
      categorySlug: catHaircare.slug,
      shortDescription: 'Lightweight heat protectant & gloss serum with Jojoba Oil',
      description: 'Bareo Leave-In Serum tame flyaways and protects hair against heat styling up to 230°C while adding high-shine glass reflection.',
      mrp: 499,
      offerPrice: 419,
      discount: 16,
      rating: 4.7,
      ratingCount: 140,
      stock: 90,
      isBestSeller: false,
      isTrending: true,
      isDoctorRecommended: false,
      isNew: false,
      isAiRecommended: false,
      skinTypes: JSON.stringify(['all']),
      concerns: JSON.stringify(['frizz', 'heat-damage', 'dullness']),
      benefits: JSON.stringify(['Heat protection up to 230°C', 'Instant flyaway taming', 'Lightweight non-sticky gloss']),
      usage: JSON.stringify(['Dispense 1-2 pumps onto palms.', 'Spread evenly over damp or dry hair lengths.']),
      keyFacts: JSON.stringify(['Non-Greasy', 'Heat Shield Complex']),
      tags: JSON.stringify(['hair-serum', 'anti-frizz', 'heat-protection']),
      soldCount: 890,
      status: 'active',
      images: ['https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=800&auto=format&fit=crop&q=80'],
      ingredients: [
        { name: 'Jojoba Oil', description: 'Mimics natural hair lipids' },
        { name: 'Vitamin E', description: 'Protects against heat oxidation' },
      ],
      faqs: [{ question: 'Does it weigh fine hair down?', answer: 'No, the fluid formula is ultra-lightweight.' }],
    },
    {
      slug: 'bareo-rice-protein-thickening-scalp-serum',
      name: 'Bareo Rice Protein Thickening Scalp Serum',
      brand: 'Bareo',
      sku: 'BAR-HC-007',
      categoryId: catHaircare.id,
      categoryName: catHaircare.name,
      categorySlug: catHaircare.slug,
      shortDescription: 'Leave-on root booster with Rice Protein & Caffeine',
      description: 'Bareo Thickening Scalp Serum plumps individual hair strands at the root for immediate volume and long-term hair density boost.',
      mrp: 699,
      offerPrice: 579,
      discount: 17,
      rating: 4.8,
      ratingCount: 96,
      stock: 65,
      isBestSeller: false,
      isTrending: true,
      isDoctorRecommended: true,
      isNew: true,
      isAiRecommended: true,
      skinTypes: JSON.stringify(['all']),
      concerns: JSON.stringify(['thinning', 'volume', 'scalp-care']),
      benefits: JSON.stringify(['Boosts hair volume at roots', 'Increases hair strand diameter', 'Non-oily water-based serum']),
      usage: JSON.stringify(['Apply 1 pipette directly onto damp or dry scalp.', 'Massage in. Do not rinse.']),
      keyFacts: JSON.stringify(['Water-Based Serum', 'No Residue']),
      tags: JSON.stringify(['scalp-serum', 'volume', 'thickening']),
      soldCount: 540,
      status: 'active',
      images: ['https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=800&auto=format&fit=crop&q=80'],
      ingredients: [
        { name: 'Hydrolyzed Rice Protein', description: 'Adds volume to hair shafts' },
        { name: 'Caffeine', description: 'Stimulates root circulation' },
      ],
      faqs: [{ question: 'Can I use this daily?', answer: 'Yes, apply daily on clean scalp.' }],
    },

    // --- CATEGORY 3: BODY CARE (7 PRODUCTS) ---
    {
      slug: 'bareo-oat-ceramide-nourishing-body-wash',
      name: 'Bareo Oat & Ceramide Nourishing Body Wash',
      brand: 'Bareo',
      sku: 'BAR-BC-001',
      categoryId: catBodycare.id,
      categoryName: catBodycare.name,
      categorySlug: catBodycare.slug,
      shortDescription: 'Creamy soap-free shower wash with Colloidal Oat & Ceramides',
      description: 'Cleanse dry, sensitive body skin without tightness. Bareo Oat Body Wash restores moisture and leaves skin velvety smooth.',
      mrp: 499,
      offerPrice: 399,
      discount: 20,
      rating: 4.9,
      ratingCount: 210,
      stock: 140,
      isBestSeller: true,
      isTrending: true,
      isDoctorRecommended: true,
      isNew: false,
      isAiRecommended: true,
      skinTypes: JSON.stringify(['dry', 'sensitive', 'normal']),
      concerns: JSON.stringify(['dryness', 'sensitivity', 'itchiness']),
      benefits: JSON.stringify(['Soap-free mild barrier cleansing', 'Soothes dry skin itchiness', 'Rich comforting lather']),
      usage: JSON.stringify(['Lather onto wet skin using a loofah or hands.', 'Rinse thoroughly.']),
      keyFacts: JSON.stringify(['Soap-Free', 'pH 5.5 Balanced', 'Dermatologist Tested']),
      tags: JSON.stringify(['body-wash', 'oatmeal', 'best-seller']),
      soldCount: 2400,
      status: 'active',
      images: ['https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&auto=format&fit=crop&q=80'],
      ingredients: [
        { name: 'Colloidal Oatmeal', description: 'Protects and calms dry skin' },
        { name: 'Ceramide NP', description: 'Restores skin lipid layer' },
      ],
      faqs: [{ question: 'Is this suitable for eczema-prone skin?', answer: 'Yes, colloidal oat is dermatologist recommended for eczema-prone skin.' }],
    },
    {
      slug: 'bareo-niacinamide-shea-butter-body-milk',
      name: 'Bareo Niacinamide & Shea Butter Body Milk Lotion',
      brand: 'Bareo',
      sku: 'BAR-BC-002',
      categoryId: catBodycare.id,
      categoryName: catBodycare.name,
      categorySlug: catBodycare.slug,
      shortDescription: 'Brightening body lotion with 5% Niacinamide & Raw Shea Butter',
      description: 'Bareo Body Milk hydrates skin for 48 hours while fading sun tan and dark spots on arms, knees, and elbows with 5% Niacinamide.',
      mrp: 649,
      offerPrice: 529,
      discount: 18,
      rating: 4.8,
      ratingCount: 190,
      stock: 115,
      isBestSeller: true,
      isTrending: true,
      isDoctorRecommended: false,
      isNew: false,
      isAiRecommended: true,
      skinTypes: JSON.stringify(['dry', 'normal', 'combination']),
      concerns: JSON.stringify(['dryness', 'tan-removal', 'pigmentation']),
      benefits: JSON.stringify(['Fades body sun tan and dark spots', '48-hour deep hydration', 'Non-sticky fast absorption']),
      usage: JSON.stringify(['Apply generously over entire body after bath.']),
      keyFacts: JSON.stringify(['5% Active Niacinamide', 'Fast Absorbing']),
      tags: JSON.stringify(['body-lotion', 'niacinamide', 'shea-butter']),
      soldCount: 1890,
      status: 'active',
      images: ['https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&auto=format&fit=crop&q=80'],
      ingredients: [
        { name: 'Niacinamide', description: 'Evens out body skin tone', concentration: '5%' },
        { name: 'Raw Shea Butter', description: 'Deeply seals in moisture' },
      ],
      faqs: [{ question: 'Does it leave white streaks?', answer: 'No, it absorbs instantly into skin.' }],
    },
    {
      slug: 'bareo-coffee-cocoa-body-exfoliating-scrub',
      name: 'Bareo Coffee & Cocoa Body Exfoliating Scrub',
      brand: 'Bareo',
      sku: 'BAR-BC-003',
      categoryId: catBodycare.id,
      categoryName: catBodycare.name,
      categorySlug: catBodycare.slug,
      shortDescription: 'Smoothing polish scrub with Arabica Coffee & Cocoa Butter',
      description: 'Buff away dead skin cells and smooth strawberry skin bumps with Bareo Coffee Body Scrub. Smells like fresh espresso.',
      mrp: 549,
      offerPrice: 449,
      discount: 18,
      rating: 4.9,
      ratingCount: 165,
      stock: 95,
      isBestSeller: false,
      isTrending: true,
      isDoctorRecommended: false,
      isNew: false,
      isAiRecommended: false,
      skinTypes: JSON.stringify(['all']),
      concerns: JSON.stringify(['rough-skin', 'ingrown-hair', 'tanning']),
      benefits: JSON.stringify(['Smooths rough strawberry legs', 'Removes dead skin tan', 'Rich coffee aroma']),
      usage: JSON.stringify(['Scoop scrub and rub in circular motions on wet body.', 'Rinse thoroughly. Use 2 times weekly.']),
      keyFacts: JSON.stringify(['Real Arabica Grounds', 'Cruelty Free']),
      tags: JSON.stringify(['body-scrub', 'coffee', 'exfoliant']),
      soldCount: 1320,
      status: 'active',
      images: ['https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&auto=format&fit=crop&q=80'],
      ingredients: [
        { name: 'Ground Arabica Coffee', description: 'Exfoliates skin texture' },
        { name: 'Cocoa Butter', description: 'Leaves skin ultra-soft' },
      ],
      faqs: [{ question: 'Can I use this on face?', answer: 'We recommend body use only as coffee particles are designed for body skin.' }],
    },
    {
      slug: 'bareo-brightening-aha-body-wash',
      name: 'Bareo Brightening AHA Exfoliating Body Wash',
      brand: 'Bareo',
      sku: 'BAR-BC-004',
      categoryId: catBodycare.id,
      categoryName: catBodycare.name,
      categorySlug: catBodycare.slug,
      shortDescription: 'Daily exfoliating wash with 5% Lactic Acid & Vitamin C',
      description: 'Smooth bumpy back acne (bacne) and rough arms with Bareo AHA Body Wash. Gently dissolves rough Keratosis Pilaris bumps.',
      mrp: 549,
      offerPrice: 459,
      discount: 16,
      rating: 4.8,
      ratingCount: 110,
      stock: 85,
      isBestSeller: false,
      isTrending: false,
      isDoctorRecommended: true,
      isNew: true,
      isAiRecommended: true,
      skinTypes: JSON.stringify(['oily', 'normal', 'combination']),
      concerns: JSON.stringify(['back-acne', 'rough-skin', 'pigmentation']),
      benefits: JSON.stringify(['Clears back acne and body breakouts', 'Smooths rough KP bumps', 'Brightens dull tone']),
      usage: JSON.stringify(['Lather over body during shower.', 'Rinse after 1-2 minutes.']),
      keyFacts: JSON.stringify(['5% Lactic Acid', 'Dermatologist Formulated']),
      tags: JSON.stringify(['aha-body-wash', 'lactic-acid', 'bacne']),
      soldCount: 780,
      status: 'active',
      images: ['https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&auto=format&fit=crop&q=80'],
      ingredients: [
        { name: 'Lactic Acid (AHA)', description: 'Gently exfoliates surface body cells', concentration: '5%' },
        { name: 'Grapefruit Extract', description: 'Natural citrus antioxidant' },
      ],
      faqs: [{ question: 'Does this help with KP (chicken skin)?', answer: 'Yes! Lactic Acid effectively dissolves keratin buildup causing KP bumps.' }],
    },
    {
      slug: 'bareo-hydrating-coconut-squalane-body-oil',
      name: 'Bareo Hydrating Coconut & Squalane Body Oil',
      brand: 'Bareo',
      sku: 'BAR-BC-005',
      categoryId: catBodycare.id,
      categoryName: catBodycare.name,
      categorySlug: catBodycare.slug,
      shortDescription: 'Fast-absorbing glowing body oil with Coconut & Squalane',
      description: 'Bareo Body Oil leaves skin with a glossy summer sheen while nourishing deep epidermal layers. Dry oil texture absorbs quickly.',
      mrp: 699,
      offerPrice: 579,
      discount: 17,
      rating: 4.7,
      ratingCount: 95,
      stock: 75,
      isBestSeller: false,
      isTrending: true,
      isDoctorRecommended: false,
      isNew: false,
      isAiRecommended: false,
      skinTypes: JSON.stringify(['dry', 'normal']),
      concerns: JSON.stringify(['dryness', 'dullness']),
      benefits: JSON.stringify(['Instant luminous body glow', 'Non-greasy dry-oil finish', 'Seals in moisture after shower']),
      usage: JSON.stringify(['Smooth over damp skin right after shower.']),
      keyFacts: JSON.stringify(['Dry-Oil Formula', '100% Botanical Oils']),
      tags: JSON.stringify(['body-oil', 'coconut', 'squalane']),
      soldCount: 640,
      status: 'active',
      images: ['https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&auto=format&fit=crop&q=80'],
      ingredients: [
        { name: 'Virgin Coconut Oil', description: 'Nourishes dry skin lipids' },
        { name: 'Plant Squalane', description: 'Provides silky satin feel' },
      ],
      faqs: [{ question: 'Will this stain clothes?', answer: 'No, the fast-absorbing dry-oil formula penetrates quickly without staining.' }],
    },
    {
      slug: 'bareo-ultra-healing-hand-cream',
      name: 'Bareo Ultra-Healing Hand & Cuticle Cream',
      brand: 'Bareo',
      sku: 'BAR-BC-006',
      categoryId: catBodycare.id,
      categoryName: catBodycare.name,
      categorySlug: catBodycare.slug,
      shortDescription: 'Nourishing hand salve with Almond Oil & Beeswax',
      description: 'Repair overworked, dry hands and cracked cuticles with Bareo Hand Cream. Forms an invisible protective glove against frequent handwashing dryness.',
      mrp: 349,
      offerPrice: 289,
      discount: 17,
      rating: 4.9,
      ratingCount: 135,
      stock: 120,
      isBestSeller: false,
      isTrending: false,
      isDoctorRecommended: true,
      isNew: false,
      isAiRecommended: false,
      skinTypes: JSON.stringify(['dry', 'sensitive', 'normal']),
      concerns: JSON.stringify(['dry-hands', 'cracked-skin']),
      benefits: JSON.stringify(['Repairs dry cracked hands', 'Softens rough cuticles', 'Non-greasy palm feel']),
      usage: JSON.stringify(['Apply to hands whenever dry.']),
      keyFacts: JSON.stringify(['Travel-Friendly', 'Barrier Defense']),
      tags: JSON.stringify(['hand-cream', 'salve', 'cuticles']),
      soldCount: 1100,
      status: 'active',
      images: ['https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&auto=format&fit=crop&q=80'],
      ingredients: [
        { name: 'Sweet Almond Oil', description: 'Deeply softens skin' },
        { name: 'Beeswax', description: 'Protective moisture shield' },
      ],
      faqs: [{ question: 'Can I use this on feet?', answer: 'Yes, it works great on dry elbows and feet too!' }],
    },
    {
      slug: 'bareo-smoothing-heel-repair-balm',
      name: 'Bareo Smoothing Heel Repair Balm',
      brand: 'Bareo',
      sku: 'BAR-BC-007',
      categoryId: catBodycare.id,
      categoryName: catBodycare.name,
      categorySlug: catBodycare.slug,
      shortDescription: 'Intense crack repair balm with 10% Urea & Salicylic Acid',
      description: 'Visibly heal cracked heels in 3 days with Bareo Heel Repair Balm. 10% Urea dissolves thick calluses while Kokum Butter softens cracks.',
      mrp: 399,
      offerPrice: 329,
      discount: 17,
      rating: 4.8,
      ratingCount: 160,
      stock: 100,
      isBestSeller: true,
      isTrending: false,
      isDoctorRecommended: true,
      isNew: false,
      isAiRecommended: true,
      skinTypes: JSON.stringify(['all']),
      concerns: JSON.stringify(['cracked-heels', 'calluses']),
      benefits: JSON.stringify(['Visibly heals cracked heels in 3 days', 'Softens tough foot calluses', 'Non-slippery absorption']),
      usage: JSON.stringify(['Apply on clean feet before bedtime.', 'Wear cotton socks overnight for best results.']),
      keyFacts: JSON.stringify(['10% Medical Urea', 'Fast 3-Day Action']),
      tags: JSON.stringify(['heel-balm', 'urea', 'foot-care']),
      soldCount: 1750,
      status: 'active',
      images: ['https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&auto=format&fit=crop&q=80'],
      ingredients: [
        { name: 'Urea', description: 'Medical grade humectant and callus softener', concentration: '10%' },
        { name: 'Salicylic Acid', description: 'Exfoliates dead heel tissue', concentration: '1%' },
      ],
      faqs: [{ question: 'How quickly does it work?', answer: 'Visible softening is noticeable within 48 to 72 hours of nightly use.' }],
    },

    // --- CATEGORY 4: BABY CARE (6 PRODUCTS) ---
    {
      slug: 'bareo-gentle-tear-free-baby-wash',
      name: 'Bareo Gentle Tear-Free Baby Head-to-Toe Wash',
      brand: 'Bareo',
      sku: 'BAR-BB-001',
      categoryId: catBabycare.id,
      categoryName: catBabycare.name,
      categorySlug: catBabycare.slug,
      shortDescription: 'Pediatrician certified tear-free wash with Chamomile & Calendula',
      description: 'Ultra-mild, tear-free cleansing for baby delicate hair and skin. Formulated with organic Chamomile and Aloe Vera to prevent dryness.',
      mrp: 449,
      offerPrice: 369,
      discount: 17,
      rating: 4.9,
      ratingCount: 180,
      stock: 130,
      isBestSeller: true,
      isTrending: true,
      isDoctorRecommended: true,
      isNew: false,
      isAiRecommended: true,
      skinTypes: JSON.stringify(['sensitive', 'baby']),
      concerns: JSON.stringify(['baby-care', 'sensitivity', 'dryness']),
      benefits: JSON.stringify(['100% Tear-Free certified', 'Hypoallergenic & pH neutral', 'Gentle head-to-toe cleansing']),
      usage: JSON.stringify(['Pump onto hands or soft washcloth.', 'Gently wash baby hair and body. Rinse with warm water.']),
      keyFacts: JSON.stringify(['Pediatrician Approved', 'Tear-Free Formula', 'Hypoallergenic']),
      tags: JSON.stringify(['baby-wash', 'tear-free', 'chamomile', 'best-seller']),
      soldCount: 2200,
      status: 'active',
      images: ['https://images.unsplash.com/photo-1519689680058-324335c77eba?w=800&auto=format&fit=crop&q=80'],
      ingredients: [
        { name: 'Organic Chamomile Water', description: 'Calms sensitive baby skin' },
        { name: 'Calendula Extract', description: 'Natural anti-inflammatory floral extract' },
      ],
      faqs: [{ question: 'Is this safe for newborns?', answer: 'Yes, pediatrician approved for use from Day 1.' }],
    },
    {
      slug: 'bareo-oat-chamomile-calming-baby-lotion',
      name: 'Bareo Oat & Chamomile Ultra-Calming Baby Lotion',
      brand: 'Bareo',
      sku: 'BAR-BB-002',
      categoryId: catBabycare.id,
      categoryName: catBabycare.name,
      categorySlug: catBabycare.slug,
      shortDescription: 'Nourishing daily lotion with Colloidal Oat & Sweet Almond Oil',
      description: 'Keep baby skin soft, hydrated, and protected against dryness. Bareo Baby Lotion absorbs quickly without sticky residue.',
      mrp: 499,
      offerPrice: 419,
      discount: 16,
      rating: 4.9,
      ratingCount: 145,
      stock: 110,
      isBestSeller: true,
      isTrending: false,
      isDoctorRecommended: true,
      isNew: false,
      isAiRecommended: true,
      skinTypes: JSON.stringify(['sensitive', 'baby']),
      concerns: JSON.stringify(['baby-care', 'dryness']),
      benefits: JSON.stringify(['24-hour baby skin moisture', 'Soothes dry skin patches', 'Gentle natural aroma']),
      usage: JSON.stringify(['Massage gently over baby body after bath.']),
      keyFacts: JSON.stringify(['Dermatologist Tested', 'Paraben & Phthalate Free']),
      tags: JSON.stringify(['baby-lotion', 'oatmeal', 'hypoallergenic']),
      soldCount: 1650,
      status: 'active',
      images: ['https://images.unsplash.com/photo-1519689680058-324335c77eba?w=800&auto=format&fit=crop&q=80'],
      ingredients: [
        { name: 'Colloidal Oatmeal', description: 'Protects delicate baby barrier' },
        { name: 'Sweet Almond Oil', description: 'Deep natural nourishment' },
      ],
      faqs: [{ question: 'Contains any synthetic perfume?', answer: 'No, free from artificial fragrances and harsh chemicals.' }],
    },
    {
      slug: 'bareo-zinc-oxide-diaper-rash-cream',
      name: 'Bareo Zinc Oxide Protective Diaper Rash Cream',
      brand: 'Bareo',
      sku: 'BAR-BB-003',
      categoryId: catBabycare.id,
      categoryName: catBabycare.name,
      categorySlug: catBabycare.slug,
      shortDescription: 'Rapid relief rash barrier cream with 15% Zinc Oxide & Shea Butter',
      description: 'Form a breathable waterproof shield against wetness and diaper friction. Bareo Diaper Cream calms redness and heals rashes fast.',
      mrp: 399,
      offerPrice: 329,
      discount: 17,
      rating: 4.9,
      ratingCount: 220,
      stock: 125,
      isBestSeller: true,
      isTrending: true,
      isDoctorRecommended: true,
      isNew: false,
      isAiRecommended: true,
      skinTypes: JSON.stringify(['sensitive', 'baby']),
      concerns: JSON.stringify(['diaper-rash', 'redness']),
      benefits: JSON.stringify(['Relieves diaper rash from 1st application', 'Creates protective moisture barrier', 'Easy to apply and wipe']),
      usage: JSON.stringify(['Clean diaper area.', 'Apply a thick layer at every diaper change.']),
      keyFacts: JSON.stringify(['15% Non-Nano Zinc Oxide', 'Pediatrician Recommended']),
      tags: JSON.stringify(['rash-cream', 'zinc-oxide', 'diaper-care']),
      soldCount: 2900,
      status: 'active',
      images: ['https://images.unsplash.com/photo-1519689680058-324335c77eba?w=800&auto=format&fit=crop&q=80'],
      ingredients: [
        { name: 'Non-Nano Zinc Oxide', description: 'Forms physical protective barrier', concentration: '15%' },
        { name: 'Raw Shea Butter', description: 'Soothes inflamed baby skin' },
      ],
      faqs: [{ question: 'Can this be used daily for prevention?', answer: 'Yes, safe to apply at every diaper change for rash prevention.' }],
    },
    {
      slug: 'bareo-sweet-almond-baby-massage-oil',
      name: 'Bareo Cold-Pressed Sweet Almond Baby Massage Oil',
      brand: 'Bareo',
      sku: 'BAR-BB-004',
      categoryId: catBabycare.id,
      categoryName: catBabycare.name,
      categorySlug: catBabycare.slug,
      shortDescription: '100% pure cold-pressed almond oil for daily baby massage',
      description: 'Strengthen baby bones and nourish skin with Bareo Cold-Pressed Almond Oil. Unrefined, light, and 100% edible-grade pure oil.',
      mrp: 549,
      offerPrice: 449,
      discount: 18,
      rating: 4.8,
      ratingCount: 160,
      stock: 90,
      isBestSeller: false,
      isTrending: true,
      isDoctorRecommended: true,
      isNew: false,
      isAiRecommended: false,
      skinTypes: JSON.stringify(['sensitive', 'baby']),
      concerns: JSON.stringify(['baby-care', 'dryness']),
      benefits: JSON.stringify(['Strengthens muscle and bone growth', 'Keeps baby skin supple and soft', '100% natural cold pressed']),
      usage: JSON.stringify(['Warm small amount between palms.', 'Gently massage baby body before bath.']),
      keyFacts: JSON.stringify(['100% Pure Almond Oil', 'No Mineral Oil', 'Unrefined']),
      tags: JSON.stringify(['massage-oil', 'almond-oil', 'baby-care']),
      soldCount: 1400,
      status: 'active',
      images: ['https://images.unsplash.com/photo-1519689680058-324335c77eba?w=800&auto=format&fit=crop&q=80'],
      ingredients: [
        { name: '100% Cold-Pressed Sweet Almond Oil', description: 'Rich in Vitamin E and essential fatty acids' },
      ],
      faqs: [{ question: 'Is this mineral oil free?', answer: 'Yes, 100% pure plant almond oil with zero mineral oil.' }],
    },
    {
      slug: 'bareo-hydrating-baby-face-body-butter',
      name: 'Bareo Hydrating Baby Face & Body Butter',
      brand: 'Bareo',
      sku: 'BAR-BB-005',
      categoryId: catBabycare.id,
      categoryName: catBabycare.name,
      categorySlug: catBabycare.slug,
      shortDescription: 'Ultra-nourishing face balm with Mango Butter & Aloe Vera',
      description: 'Protect baby cheeks against cold wind drying and drool rash with Bareo Baby Face Butter. Rich soothing balm texture.',
      mrp: 499,
      offerPrice: 399,
      discount: 20,
      rating: 4.7,
      ratingCount: 90,
      stock: 80,
      isBestSeller: false,
      isTrending: false,
      isDoctorRecommended: false,
      isNew: true,
      isAiRecommended: false,
      skinTypes: JSON.stringify(['sensitive', 'baby']),
      concerns: JSON.stringify(['drool-rash', 'dry-cheeks']),
      benefits: JSON.stringify(['Protects baby cheeks from drool rash', 'Intense soothing moisture', 'Gentle non-stinging formula']),
      usage: JSON.stringify(['Dab gently onto baby cheeks, chin, and dry patches.']),
      keyFacts: JSON.stringify(['Pediatrician Tested', 'Lanolin-Free']),
      tags: JSON.stringify(['baby-butter', 'drool-rash', 'mango-butter']),
      soldCount: 520,
      status: 'active',
      images: ['https://images.unsplash.com/photo-1519689680058-324335c77eba?w=800&auto=format&fit=crop&q=80'],
      ingredients: [
        { name: 'Mango Seed Butter', description: 'Softens dry patches' },
        { name: 'Organic Aloe Vera', description: 'Cools irritated cheeks' },
      ],
      faqs: [{ question: 'Is it safe if baby licks near lips?', answer: 'Yes, made with 100% food-grade botanical ingredients.' }],
    },
    {
      slug: 'bareo-talc-free-botanical-baby-powder',
      name: 'Bareo Soothing Botanical Baby Powder (Talc-Free)',
      brand: 'Bareo',
      sku: 'BAR-BB-006',
      categoryId: catBabycare.id,
      categoryName: catBabycare.name,
      categorySlug: catBabycare.slug,
      shortDescription: '100% Talc-Free dusting powder with Arrowroot & Lavender',
      description: 'Keep baby skin folds fresh and dry naturally. 100% Talc-Free cornstarch and arrowroot powder absorbs excess dampness without clogging pores.',
      mrp: 349,
      offerPrice: 279,
      discount: 20,
      rating: 4.9,
      ratingCount: 170,
      stock: 110,
      isBestSeller: true,
      isTrending: true,
      isDoctorRecommended: true,
      isNew: false,
      isAiRecommended: true,
      skinTypes: JSON.stringify(['sensitive', 'baby']),
      concerns: JSON.stringify(['sweat-folds', 'chafing']),
      benefits: JSON.stringify(['100% Talc-Free safer formulation', 'Absorbs excess dampness in skin folds', 'Prevents sweat chafing']),
      usage: JSON.stringify(['Dust powder onto hands first, then pat gently on baby skin folds.']),
      keyFacts: JSON.stringify(['100% Talc Free', 'Non-Toxic', 'Cornstarch & Arrowroot']),
      tags: JSON.stringify(['baby-powder', 'talc-free', 'arrowroot']),
      soldCount: 1980,
      status: 'active',
      images: ['https://images.unsplash.com/photo-1519689680058-324335c77eba?w=800&auto=format&fit=crop&q=80'],
      ingredients: [
        { name: 'Organic Arrowroot Powder', description: 'Absorbs moisture gently' },
        { name: 'Corn Starch', description: 'Keeps skin soft and dry' },
      ],
      faqs: [{ question: 'Why talc-free?', answer: 'Talc-free powders remove inhalation risks and are pediatrician recommended.' }],
    },
  ]

  for (const product of productsData) {
    const { images, ingredients, faqs, ...productFields } = product

    const createdProduct = await prisma.product.create({
      data: {
        ...productFields,
        images: {
          create: images.map((url) => ({ url, alt: product.name })),
        },
        ingredients: {
          create: ingredients,
        },
        faqs: {
          create: faqs,
        },
      },
    })

    // Seed 1 sample review per product
    await prisma.review.create({
      data: {
        productId: createdProduct.id,
        userId: user.id,
        userName: 'Ananya Sharma',
        rating: 5,
        title: 'Amazing quality product!',
        comment: `Loved using ${product.name}! Showed visible results within a few days of consistent use. Highly recommended for ${product.categoryName}.`,
        date: '2026-08-01',
        verified: true,
        helpful: 12,
      },
    })
  }

  console.log(`✨ Successfully created ${productsData.length} Bareo Products with Images, Ingredients, FAQs & Reviews!`)

  // 4. Create Coupons
  const couponsData = [
    {
      code: 'WELCOME10',
      description: 'Get 10% OFF on your first Bareo order',
      discountType: 'percent',
      value: 10,
      minOrder: 499,
      maxDiscount: 200,
      validTill: '2026-12-31',
      active: true,
    },
    {
      code: 'BAREO20',
      description: 'Flat 20% OFF on orders above ₹999',
      discountType: 'percent',
      value: 20,
      minOrder: 999,
      maxDiscount: 500,
      validTill: '2026-12-31',
      active: true,
    },
    {
      code: 'FLAT100',
      description: 'Flat ₹100 OFF on orders above ₹699',
      discountType: 'flat',
      value: 100,
      minOrder: 699,
      validTill: '2026-12-31',
      active: true,
    },
  ]

  for (const coupon of couponsData) {
    await prisma.coupon.create({ data: coupon })
  }
  console.log(`🎟️ Created ${couponsData.length} Coupons`)

  // 5. Create Offers
  const offersData = [
    {
      title: 'Bareo Skincare Launch Deal',
      subtitle: 'Flat 15% OFF on all Skincare Serums & Moisturizers',
      code: 'BAREO20',
      badge: 'Bareo Special',
      background: 'from-amber-600 to-rose-600',
      discountLabel: '15% OFF',
      type: 'flash',
    },
    {
      title: 'Baby Care Gentle Bundle',
      subtitle: 'Buy Baby Wash & Lotion, Get Talc-Free Powder Free',
      code: 'WELCOME10',
      badge: 'Parent Special',
      background: 'from-teal-600 to-emerald-600',
      discountLabel: 'Combo Deal',
      type: 'combo',
    },
  ]

  for (const offer of offersData) {
    await prisma.offer.create({ data: offer })
  }
  console.log(`🔥 Created ${offersData.length} Promotional Offers`)

  console.log('✅ Bareo Prisma Database Seeding Completed Successfully!')
}

main()
  .catch((e) => {
    console.error('❌ Seeding Error:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
