/**
 * Centralized Domain Error Codes for Bareo Backend Platform.
 */
export const ErrorCodes = {
  // Authentication & User Domain
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_USER_EXISTS: 'AUTH_USER_EXISTS',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',

  // Product Catalog Domain
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PRODUCT_OUT_OF_STOCK: 'PRODUCT_OUT_OF_STOCK',
  PRODUCT_SLUG_EXISTS: 'PRODUCT_SLUG_EXISTS',

  // Cart Domain
  CART_NOT_FOUND: 'CART_NOT_FOUND',
  CART_ITEM_NOT_FOUND: 'CART_ITEM_NOT_FOUND',
  CART_MAX_QUANTITY_EXCEEDED: 'CART_MAX_QUANTITY_EXCEEDED',
  CART_STOCK_EXCEEDED: 'CART_STOCK_EXCEEDED',

  // Coupon Domain
  COUPON_NOT_FOUND: 'COUPON_NOT_FOUND',
  COUPON_EXPIRED: 'COUPON_EXPIRED',
  COUPON_INACTIVE: 'COUPON_INACTIVE',
  COUPON_MIN_ORDER_NOT_MET: 'COUPON_MIN_ORDER_NOT_MET',
  COUPON_CODE_EXISTS: 'COUPON_CODE_EXISTS',

  // Order Domain
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_INVALID_PAYLOAD: 'ORDER_INVALID_PAYLOAD',

  // AI Domain
  AI_CONSULTATION_INVALID: 'AI_CONSULTATION_INVALID',

  // Request & Validation Domain
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes]
