import mongoose from 'mongoose'
import bcrypt from 'bcryptjs'
import dotenv from 'dotenv'
import dns from 'dns'
import { User } from './models/User.model.js'
import { Category } from './models/Category.model.js'
import { Product } from './models/Product.model.js'
import { Coupon } from './models/Coupon.model.js'
import { Offer } from './models/Offer.model.js'

dotenv.config()

// Fix for Windows Node.js SRV DNS lookup issues (querySrv EBADNAME)
try {
  dns.setDefaultResultOrder('ipv4first')
  dns.setServers(['8.8.8.8', '1.1.1.1'])
} catch {
  // Ignore DNS override errors if restricted
}

const MONGODB_URI =
  process.env.DATABASE_URL ||
  process.env.MONGODB_URI ||
  'mongodb://127.0.0.1:27017/lumina_skin'

async function seed() {
  console.log('🌱 Connecting to MongoDB via Mongoose for Full 28-Product Seeding...')
  await mongoose.connect(MONGODB_URI, {
    serverSelectionTimeoutMS: 10000,
  })

  // Clear existing collections
  await Promise.all([
    User.deleteMany({}),
    Category.deleteMany({}),
    Product.deleteMany({}),
    Coupon.deleteMany({}),
    Offer.deleteMany({}),
  ])

  console.log('🧹 Cleared existing database collections.')

  // 1. Seed Users
  const adminPassword = await bcrypt.hash('admin123', 10)
  const userPassword = await bcrypt.hash('user123', 10)

  await User.create({
    name: 'Bareo Admin',
    email: 'admin@luminaskin.com',
    password: adminPassword,
    phone: '+91 9876543210',
    role: 'ADMIN',
  })

  await User.create({
    name: 'Bareo Admin',
    email: 'admin@bareo.in',
    password: adminPassword,
    phone: '+91 9876543212',
    role: 'ADMIN',
  })

  await User.create({
    name: 'Ananya Sharma',
    email: 'ananya@example.com',
    password: userPassword,
    phone: '+91 9876543211',
    role: 'USER',
  })

  await User.create({
    name: 'Bareo Customer',
    email: 'user@bareo.in',
    password: userPassword,
    phone: '+91 9876543210',
    role: 'USER',
  })

  console.log('👤 Seeded Users (Admin & Customer).')

  // 2. Seed Bareo Categories (4 Categories)
  const categories = await Category.insertMany([
    { name: 'Skincare', slug: 'skincare', image: '/images/products/serum.png', description: 'Clean, dermatologically formulated skincare products engineered for skin barrier repair and radiance.' },
    { name: 'Hair Care', slug: 'hair-care', image: '/images/products/shampoo.png', description: 'Scalp-first hair care solutions infused with botanicals and active proteins for hair vitality.' },
    { name: 'Body Care', slug: 'body-care', image: '/images/products/bodywash.png', description: 'Nourishing body washes, scrubs, and lotions that restore skin elasticity and deep moisture.' },
    { name: 'Baby Care', slug: 'baby-care', image: '/images/products/babyMoisturizer.png', description: 'Hypoallergenic, ultra-gentle formulas designed for delicate baby skin and scalp.' },
  ])

  console.log('📦 Seeded Bareo Product Categories.')

  // 3. Seed Bareo 28 Products
  await Product.insertMany([
    // --- CATEGORY 1: Skincare (8 Products) ---
    {
      sku: 'BAR-SK-001',
      slug: 'bareo-cica-niacinamide-calming-serum',
      name: 'Bareo Cica & Niacinamide Calming Serum',
      brand: 'Bareo',
      categoryId: categories[0]._id.toString(),
      categoryName: categories[0].name,
      categorySlug: categories[0].slug,
      shortDescription: 'Soothing barrier serum with 10% Niacinamide & 5% Centella',
      description: 'Bareo Cica & Niacinamide Calming Serum repairs damaged skin barriers, reduces redness, and balances oil production with pure botanical actives.',
      mrp: 399, offerPrice: 299, discount: 25,
      rating: 4.9,
      ratingCount: 184,
      stock: 95,
      isBestSeller: true,
      isTrending: true,
      isDoctorRecommended: true,
      isNewProduct: false,
      isAiRecommended: true,
      skinTypes: ['sensitive', 'oily', 'combination', 'dry', 'normal'],
      concerns: ['redness', 'acne', 'sensitivity'],
      benefits: ['Calms redness and inflammation instantly', 'Strengthens moisture barrier', 'Tightens enlarged pores'],
      usage: ['Apply 3-4 drops onto clean face.', 'Gently pat until absorbed.'],
      keyFacts: ['Dermatologically Tested', 'Fragrance-Free', '100% Vegan'],
      tags: ['niacinamide', 'cica', 'barrier-repair'],
      images: [{ url: '/images/products/bareo-cica-serum.png', alt: 'Bareo Cica Serum' }],
      status: 'active',
    },
    {
      sku: 'BAR-SK-002',
      slug: 'bareo-dewy-barrier-hyaluronic-hydrator',
      name: 'Bareo Dewy Barrier Hyaluronic Hydrator',
      brand: 'Bareo',
      categoryId: categories[0]._id.toString(),
      categoryName: categories[0].name,
      categorySlug: categories[0].slug,
      shortDescription: 'Multi-molecular hydration gel cream with Squalane & Ceramides',
      description: 'Quench thirsty skin with Bareo Dewy Barrier Hydrator. Infused with 5 molecular weights of Hyaluronic Acid and Plant Squalane for 72-hour moisture retention.',
      mrp: 399, offerPrice: 299, discount: 25,
      rating: 4.8,
      ratingCount: 156,
      stock: 110,
      isBestSeller: true,
      isTrending: true,
      isDoctorRecommended: true,
      isNewProduct: false,
      isAiRecommended: true,
      skinTypes: ['dry', 'normal', 'sensitive', 'combination'],
      concerns: ['dryness', 'dehydration'],
      benefits: ['Delivers 72 hours of uninterrupted hydration', 'Locks moisture with Squalane'],
      usage: ['Take a pea-sized amount.', 'Smooth evenly over face.'],
      keyFacts: ['Oil-Free Gel', 'Non-Comedogenic'],
      tags: ['hyaluronic-acid', 'squalane', 'moisturizer'],
      images: [{ url: '/images/products/bareo-barrier-hydrator.png', alt: 'Bareo Dewy Barrier' }],
      status: 'active',
    },
    {
      sku: 'BAR-SK-003',
      slug: 'bareo-rice-water-alpha-arbutin-essence',
      name: 'Bareo Rice Water & Alpha Arbutin Essence',
      brand: 'Bareo',
      categoryId: categories[0]._id.toString(),
      categoryName: categories[0].name,
      categorySlug: categories[0].slug,
      shortDescription: 'Illuminating toner essence with 70% Fermented Rice Water & 2% Alpha Arbutin',
      description: 'Bareo Brightening Essence combines traditional Asian rice ferment technology with modern Alpha Arbutin to fade sun spots and restore natural radiance.',
      mrp: 449, offerPrice: 349, discount: 22,
      rating: 4.7,
      ratingCount: 112,
      stock: 80,
      isBestSeller: false,
      isTrending: true,
      isDoctorRecommended: false,
      isNewProduct: true,
      isAiRecommended: true,
      skinTypes: ['normal', 'combination', 'dry'],
      concerns: ['pigmentation', 'dullness'],
      benefits: ['Fades dark marks and hyperpigmentation', 'Refines skin texture'],
      usage: ['Press gently onto face using palms.'],
      keyFacts: ['Alcohol-Free', 'Bio-Fermented'],
      tags: ['rice-water', 'alpha-arbutin'],
      images: [{ url: '/images/products/bareo-cica-serum.png', alt: 'Bareo Rice Essence' }],
      status: 'active',
    },
    {
      sku: 'BAR-SK-004',
      slug: 'bareo-salicylic-acid-tea-tree-cleanser',
      name: 'Bareo Salicylic Acid & Tea Tree Cleanser',
      brand: 'Bareo',
      categoryId: categories[0]._id.toString(),
      categoryName: categories[0].name,
      categorySlug: categories[0].slug,
      shortDescription: 'Deep pore clarifying wash with 2% BHA & Australian Tea Tree',
      description: 'Dissolve stubborn blackheads, unclog pores, and calm active acne with Bareo Salicylic Acid Cleanser. Sulphate-free pH 5.5 formula.',
      mrp: 299, offerPrice: 229, discount: 23,
      rating: 4.8,
      ratingCount: 230,
      stock: 140,
      isBestSeller: true,
      isTrending: false,
      isDoctorRecommended: true,
      isNewProduct: false,
      isAiRecommended: true,
      skinTypes: ['oily', 'combination'],
      concerns: ['acne', 'oiliness', 'blackheads'],
      benefits: ['Unclogs pores', 'Controls excess sebum'],
      usage: ['Massage 1 pump on wet skin for 60s.'],
      keyFacts: ['Sulphate-Free', 'pH 5.5'],
      tags: ['salicylic-acid', 'cleanser'],
      images: [{ url: '/images/products/bareo-facial-cleanser.png', alt: 'Bareo Salicylic Cleanser' }],
      status: 'active',
    },
    {
      sku: 'BAR-SK-005',
      slug: 'bareo-invisible-shield-fluid-sunscreen-spf50',
      name: 'Bareo Invisible Shield Fluid Sunscreen SPF 50 PA++++',
      brand: 'Bareo',
      categoryId: categories[0]._id.toString(),
      categoryName: categories[0].name,
      categorySlug: categories[0].slug,
      shortDescription: 'Ultra-lightweight fluid sunscreen with Zero White Cast',
      description: 'Bareo Invisible Shield SPF 50 provides high-performance UVA/UVB protection with an airy, invisible matte finish. Infused with Vitamin E and Ceramides.',
      mrp: 429, offerPrice: 329, discount: 23,
      rating: 4.9,
      ratingCount: 310,
      stock: 150,
      isBestSeller: true,
      isTrending: true,
      isDoctorRecommended: true,
      isNewProduct: false,
      isAiRecommended: true,
      skinTypes: ['oily', 'combination', 'dry', 'normal', 'sensitive'],
      concerns: ['sun-protection', 'aging'],
      benefits: ['Broad-spectrum SPF 50 PA++++', 'Zero white cast'],
      usage: ['Apply 2 fingers length on face before sun exposure.'],
      keyFacts: ['Reef-Safe', 'Non-Greasy'],
      tags: ['sunscreen', 'spf50'],
      images: [{ url: '/images/products/bareo-fluid-sunscreen.png', alt: 'Bareo Fluid Sunscreen' }],
      status: 'active',
    },
    {
      sku: 'BAR-SK-006',
      slug: 'bareo-peptide-repair-night-cream',
      name: 'Bareo Peptide Repair & Renewal Night Cream',
      brand: 'Bareo',
      categoryId: categories[0]._id.toString(),
      categoryName: categories[0].name,
      categorySlug: categories[0].slug,
      shortDescription: 'Nightly collagen boost cream with 5-Peptide Complex & Squalane',
      description: 'Awaken to plump, firm skin with Bareo Peptide Repair Cream. Works overnight to stimulate natural collagen, rebuild skin density, and smooth fine lines.',
      mrp: 399, offerPrice: 299, discount: 25,
      rating: 4.8,
      ratingCount: 88,
      stock: 65,
      isBestSeller: false,
      isTrending: true,
      isDoctorRecommended: true,
      isNewProduct: false,
      isAiRecommended: true,
      skinTypes: ['dry', 'normal', 'combination'],
      concerns: ['aging', 'fine-lines'],
      benefits: ['Boosts skin elasticity', 'Smooths fine lines'],
      usage: ['Smooth generous layer nightly.'],
      keyFacts: ['Clinical Peptides', 'Cruelty Free'],
      tags: ['night-cream', 'peptides'],
      images: [{ url: '/images/products/bareo-barrier-hydrator.png', alt: 'Bareo Night Cream' }],
      status: 'active',
    },
    {
      sku: 'BAR-SK-007',
      slug: 'bareo-clarifying-aha-bha-exfoliating-peel',
      name: 'Bareo Clarifying AHA + BHA Exfoliating Peel',
      brand: 'Bareo',
      categoryId: categories[0]._id.toString(),
      categoryName: categories[0].name,
      categorySlug: categories[0].slug,
      shortDescription: '10-minute rinse-off peeling wash with 10% Glycolic Acid & 2% Salicylic Acid',
      description: 'Transform rough, dull skin in 10 minutes with Bareo Exfoliating Peel. Removes dead surface cells and clears congested pores for instant baby-smooth skin.',
      mrp: 399, offerPrice: 299, discount: 25,
      rating: 4.7,
      ratingCount: 94,
      stock: 75,
      isBestSeller: false,
      isTrending: false,
      isDoctorRecommended: true,
      isNewProduct: true,
      isAiRecommended: false,
      skinTypes: ['oily', 'combination', 'normal'],
      concerns: ['dullness', 'uneven-texture'],
      benefits: ['Smooths rough skin texture', 'Fades surface dullness'],
      usage: ['Leave on clean face for 10 mins maximum then rinse.'],
      keyFacts: ['Rinse-Off Peel', 'Weekly Treatment'],
      tags: ['exfoliant', 'aha-bha'],
      images: [{ url: '/images/products/bareo-facial-cleanser.png', alt: 'Bareo Exfoliating Peel' }],
      status: 'active',
    },
    {
      sku: 'BAR-SK-008',
      slug: 'bareo-squalane-vitamin-c-glow-face-oil',
      name: 'Bareo Squalane & Vitamin C Glow Face Oil',
      brand: 'Bareo',
      categoryId: categories[0]._id.toString(),
      categoryName: categories[0].name,
      categorySlug: categories[0].slug,
      shortDescription: 'Non-comedogenic radiance oil with 15% Vitamin C & Plant Squalane',
      description: 'Bareo Glow Face Oil locks in hydration while delivering a concentrated dose of stable 15% Vitamin C for an instant golden-hour radiance.',
      mrp: 449, offerPrice: 349, discount: 22,
      rating: 4.9,
      ratingCount: 140,
      stock: 60,
      isBestSeller: true,
      isTrending: true,
      isDoctorRecommended: false,
      isNewProduct: false,
      isAiRecommended: true,
      skinTypes: ['dry', 'normal', 'combination'],
      concerns: ['dullness', 'dryness'],
      benefits: ['Instant luminous skin glow', 'Non-comedogenic oil'],
      usage: ['Warm 2 drops on palms and press into skin.'],
      keyFacts: ['Sugarcane Squalane', 'Pore-Safe'],
      tags: ['face-oil', 'vitamin-c'],
      images: [{ url: '/images/products/bareo-cica-serum.png', alt: 'Bareo Glow Oil' }],
      status: 'active',
    },

    // --- CATEGORY 2: Hair Care (7 Products) ---
    {
      sku: 'BAR-HC-001',
      slug: 'bareo-rosemary-biotin-scalp-shampoo',
      name: 'Bareo Rosemary & Biotin Scalp Revitalizing Shampoo',
      brand: 'Bareo',
      categoryId: categories[1]._id.toString(),
      categoryName: categories[1].name,
      categorySlug: categories[1].slug,
      shortDescription: 'Sulphate-free scalp stimulating shampoo with Rosemary Oil & Biotin',
      description: 'Strengthen hair follicles and reduce hair fall with Bareo Rosemary & Biotin Shampoo. Gently cleanses scalp buildup while stimulating micro-circulation.',
      mrp: 399, offerPrice: 279, discount: 30,
      rating: 4.8,
      ratingCount: 260,
      stock: 120,
      isBestSeller: true,
      isTrending: true,
      isDoctorRecommended: true,
      isNewProduct: false,
      isAiRecommended: true,
      skinTypes: ['all'],
      concerns: ['hair-fall', 'scalp-care'],
      benefits: ['Reduces hair fall', 'Stimulates new root growth'],
      usage: ['Massage onto wet scalp for 2 minutes and rinse.'],
      keyFacts: ['Sulphate-Free', 'Color-Safe'],
      tags: ['shampoo', 'rosemary'],
      images: [{ url: '/images/products/bareo-rosemary-shampoo.png', alt: 'Bareo Rosemary Shampoo' }],
      status: 'active',
    },
    {
      sku: 'BAR-HC-002',
      slug: 'bareo-argan-silk-peptide-conditioner',
      name: 'Bareo Argan Oil & Silk Peptide Hydrating Conditioner',
      brand: 'Bareo',
      categoryId: categories[1]._id.toString(),
      categoryName: categories[1].name,
      categorySlug: categories[1].slug,
      shortDescription: 'Deep moisturizing conditioner with Pure Moroccan Argan Oil',
      description: 'Bareo Argan Oil Conditioner smooths dry frizz, detangles knots, and restores silky shine to damaged hair strands.',
      mrp: 449, offerPrice: 349, discount: 22,
      rating: 4.7,
      ratingCount: 175,
      stock: 100,
      isBestSeller: false,
      isTrending: true,
      isDoctorRecommended: false,
      isNewProduct: false,
      isAiRecommended: true,
      skinTypes: ['all'],
      concerns: ['frizz', 'dryness'],
      benefits: ['Detangles knots instantly', 'Restores silky shine'],
      usage: ['Apply to hair lengths for 3 minutes then rinse.'],
      keyFacts: ['Silicone-Free', 'Argan Oil Infused'],
      tags: ['conditioner', 'argan-oil'],
      images: [{ url: '/images/products/bareo-rosemary-shampoo.png', alt: 'Bareo Conditioner' }],
      status: 'active',
    },
    {
      sku: 'BAR-HC-003',
      slug: 'bareo-rosemary-root-nourishing-hair-oil',
      name: 'Bareo Rosemary Root Nourishing Hair Oil',
      brand: 'Bareo',
      categoryId: categories[1]._id.toString(),
      categoryName: categories[1].name,
      categorySlug: categories[1].slug,
      shortDescription: 'Cold-pressed scalp oil with Rosemary, Bhringraj & Amla',
      description: 'Bareo Rosemary Root Oil is a traditional Ayurvedic blend enhanced with cold-pressed Rosemary to nourish hair follicles and boost density.',
      mrp: 449, offerPrice: 349, discount: 22,
      rating: 4.9,
      ratingCount: 290,
      stock: 130,
      isBestSeller: true,
      isTrending: true,
      isDoctorRecommended: true,
      isNewProduct: false,
      isAiRecommended: true,
      skinTypes: ['all'],
      concerns: ['hair-fall', 'thinning'],
      benefits: ['Promotes hair density', 'Nourishes dry scalp roots'],
      usage: ['Apply on scalp 1 hour before hair wash.'],
      keyFacts: ['100% Cold Pressed', 'No Mineral Oil'],
      tags: ['hair-oil', 'rosemary'],
      images: [{ url: '/images/products/bareo-scalp-hair-oil.png', alt: 'Bareo Hair Oil' }],
      status: 'active',
    },
    {
      sku: 'BAR-HC-004',
      slug: 'bareo-scalp-balance-exfoliating-scrub',
      name: 'Bareo Scalp Balance Exfoliating Scrub',
      brand: 'Bareo',
      categoryId: categories[1]._id.toString(),
      categoryName: categories[1].name,
      categorySlug: categories[1].slug,
      shortDescription: 'Clarifying sea salt scrub for scalp detox & dandruff control',
      description: 'Bareo Scalp Balance Scrub gently buffs away dead skin flakes, product buildup, and excess oil for a squeaky clean, refreshed scalp environment.',
      mrp: 299, offerPrice: 229, discount: 23,
      rating: 4.7,
      ratingCount: 82,
      stock: 70,
      isBestSeller: false,
      isTrending: true,
      isDoctorRecommended: false,
      isNewProduct: true,
      isAiRecommended: false,
      skinTypes: ['all'],
      concerns: ['dandruff', 'scalp-care'],
      benefits: ['Clears scalp product buildup', 'Soothes itchiness'],
      usage: ['Massage onto wet scalp before shampooing.'],
      keyFacts: ['Sea Salt Crystals', 'Tea Tree Infused'],
      tags: ['scalp-scrub', 'dandruff'],
      images: [{ url: '/images/products/bareo-rosemary-shampoo.png', alt: 'Bareo Scalp Scrub' }],
      status: 'active',
    },
    {
      sku: 'BAR-HC-005',
      slug: 'bareo-keratin-intense-repair-mask',
      name: 'Bareo Keratin Intense Repair Hair Mask',
      brand: 'Bareo',
      categoryId: categories[1]._id.toString(),
      categoryName: categories[1].name,
      categorySlug: categories[1].slug,
      shortDescription: 'Deep conditioning treatment mask with Plant Keratin & Macadamia',
      description: 'Restore strength to over-processed, heat-damaged hair with Bareo Keratin Repair Mask. Rebuilds protein bonds and stops breakage.',
      mrp: 399, offerPrice: 279, discount: 30,
      rating: 4.8,
      ratingCount: 104,
      stock: 60,
      isBestSeller: false,
      isTrending: false,
      isDoctorRecommended: true,
      isNewProduct: false,
      isAiRecommended: true,
      skinTypes: ['all'],
      concerns: ['damage', 'breakage'],
      benefits: ['Reduces hair breakage', 'Deep protein treatment'],
      usage: ['Leave on damp hair for 10-15 minutes then rinse.'],
      keyFacts: ['Plant Keratin', 'Heat Repair'],
      tags: ['hair-mask', 'keratin'],
      images: [{ url: '/images/products/bareo-rosemary-shampoo.png', alt: 'Bareo Keratin Mask' }],
      status: 'active',
    },
    {
      sku: 'BAR-HC-006',
      slug: 'bareo-anti-frizz-gloss-leave-in-serum',
      name: 'Bareo Anti-Frizz Gloss Leave-In Hair Serum',
      brand: 'Bareo',
      categoryId: categories[1]._id.toString(),
      categoryName: categories[1].name,
      categorySlug: categories[1].slug,
      shortDescription: 'Lightweight heat protectant & gloss serum with Jojoba Oil',
      description: 'Bareo Leave-In Serum tame flyaways and protects hair against heat styling up to 230°C while adding high-shine glass reflection.',
      mrp: 449, offerPrice: 349, discount: 22,
      rating: 4.7,
      ratingCount: 140,
      stock: 90,
      isBestSeller: false,
      isTrending: true,
      isDoctorRecommended: false,
      isNewProduct: false,
      isAiRecommended: false,
      skinTypes: ['all'],
      concerns: ['frizz', 'heat-damage'],
      benefits: ['Protects against heat up to 230°C', 'Instant flyaway taming'],
      usage: ['Spread 1 pump on towel dried hair before blow drying.'],
      keyFacts: ['Heat Protection', 'Gloss Finish'],
      tags: ['hair-serum', 'anti-frizz'],
      images: [{ url: '/images/products/bareo-scalp-hair-oil.png', alt: 'Bareo Leave In Serum' }],
      status: 'active',
    },
    {
      sku: 'BAR-HC-007',
      slug: 'bareo-rice-protein-thickening-scalp-serum',
      name: 'Bareo Rice Protein Thickening Scalp Serum',
      brand: 'Bareo',
      categoryId: categories[1]._id.toString(),
      categoryName: categories[1].name,
      categorySlug: categories[1].slug,
      shortDescription: 'Leave-on root booster with Rice Protein & Caffeine',
      description: 'Bareo Thickening Scalp Serum plumps individual hair strands at the root for immediate volume and long-term hair density boost.',
      mrp: 449, offerPrice: 349, discount: 22,
      rating: 4.8,
      ratingCount: 96,
      stock: 65,
      isBestSeller: false,
      isTrending: true,
      isDoctorRecommended: true,
      isNewProduct: true,
      isAiRecommended: true,
      skinTypes: ['all'],
      concerns: ['thinning', 'volume'],
      benefits: ['Plumps root hair volume', 'Non-greasy serum'],
      usage: ['Apply 1 pipette on scalp daily.'],
      keyFacts: ['Water-Based', 'Root Booster'],
      tags: ['scalp-serum', 'volume'],
      images: [{ url: '/images/products/bareo-rosemary-shampoo.png', alt: 'Bareo Scalp Serum' }],
      status: 'active',
    },

    // --- CATEGORY 3: Body Care (7 Products) ---
    {
      sku: 'BAR-BC-001',
      slug: 'bareo-oat-ceramide-nourishing-body-wash',
      name: 'Bareo Oat & Ceramide Nourishing Body Wash',
      brand: 'Bareo',
      categoryId: categories[2]._id.toString(),
      categoryName: categories[2].name,
      categorySlug: categories[2].slug,
      shortDescription: 'Creamy soap-free shower wash with Colloidal Oat & Ceramides',
      description: 'Cleanse dry, sensitive body skin without tightness. Bareo Oat Body Wash restores moisture and leaves skin velvety smooth.',
      mrp: 329, offerPrice: 239, discount: 27,
      rating: 4.9,
      ratingCount: 210,
      stock: 140,
      isBestSeller: true,
      isTrending: true,
      isDoctorRecommended: true,
      isNewProduct: false,
      isAiRecommended: true,
      skinTypes: ['dry', 'sensitive', 'normal'],
      concerns: ['dryness', 'sensitivity'],
      benefits: ['Soap-free gentle wash', 'Calms dry skin tightness'],
      usage: ['Lather onto wet body during shower.'],
      keyFacts: ['Soap-Free', 'pH 5.5'],
      tags: ['body-wash', 'oatmeal'],
      images: [{ url: '/images/products/bareo-oat-body-wash.png', alt: 'Bareo Oat Body Wash' }],
      status: 'active',
    },
    {
      sku: 'BAR-BC-002',
      slug: 'bareo-niacinamide-shea-butter-body-milk',
      name: 'Bareo Niacinamide & Shea Butter Body Milk Lotion',
      brand: 'Bareo',
      categoryId: categories[2]._id.toString(),
      categoryName: categories[2].name,
      categorySlug: categories[2].slug,
      shortDescription: 'Brightening body lotion with 5% Niacinamide & Raw Shea Butter',
      description: 'Bareo Body Milk hydrates skin for 48 hours while fading sun tan and dark spots on arms, knees, and elbows with 5% Niacinamide.',
      mrp: 349, offerPrice: 269, discount: 22,
      rating: 4.8,
      ratingCount: 190,
      stock: 115,
      isBestSeller: true,
      isTrending: true,
      isDoctorRecommended: false,
      isNewProduct: false,
      isAiRecommended: true,
      skinTypes: ['dry', 'normal', 'combination'],
      concerns: ['dryness', 'tan-removal'],
      benefits: ['Fades body sun tan', '48-hour moisture lock'],
      usage: ['Apply all over body after bathing.'],
      keyFacts: ['5% Niacinamide', 'Raw Shea Butter'],
      tags: ['body-lotion', 'niacinamide'],
      images: [{ url: '/images/products/bareo-shea-body-lotion.png', alt: 'Bareo Body Lotion' }],
      status: 'active',
    },
    {
      sku: 'BAR-BC-003',
      slug: 'bareo-coffee-cocoa-body-exfoliating-scrub',
      name: 'Bareo Coffee & Cocoa Body Exfoliating Scrub',
      brand: 'Bareo',
      categoryId: categories[2]._id.toString(),
      categoryName: categories[2].name,
      categorySlug: categories[2].slug,
      shortDescription: 'Smoothing polish scrub with Arabica Coffee & Cocoa Butter',
      description: 'Buff away dead skin cells and smooth strawberry skin bumps with Bareo Coffee Body Scrub. Smells like fresh espresso.',
      mrp: 299, offerPrice: 229, discount: 23,
      rating: 4.9,
      ratingCount: 165,
      stock: 95,
      isBestSeller: false,
      isTrending: true,
      isDoctorRecommended: false,
      isNewProduct: false,
      isAiRecommended: false,
      skinTypes: ['all'],
      concerns: ['rough-skin', 'tanning'],
      benefits: ['Smooths strawberry legs', 'Removes dead skin tan'],
      usage: ['Scrub gently on wet body twice weekly.'],
      keyFacts: ['Arabica Grounds', 'Rich Cocoa Butter'],
      tags: ['body-scrub', 'coffee'],
      images: [{ url: '/images/products/bareo-oat-body-wash.png', alt: 'Bareo Body Scrub' }],
      status: 'active',
    },
    {
      sku: 'BAR-BC-004',
      slug: 'bareo-brightening-aha-body-wash',
      name: 'Bareo Brightening AHA Exfoliating Body Wash',
      brand: 'Bareo',
      categoryId: categories[2]._id.toString(),
      categoryName: categories[2].name,
      categorySlug: categories[2].slug,
      shortDescription: 'Daily exfoliating wash with 5% Lactic Acid & Vitamin C',
      description: 'Smooth bumpy back acne (bacne) and rough arms with Bareo AHA Body Wash. Gently dissolves rough Keratosis Pilaris bumps.',
      mrp: 329, offerPrice: 239, discount: 27,
      rating: 4.8,
      ratingCount: 110,
      stock: 85,
      isBestSeller: false,
      isTrending: false,
      isDoctorRecommended: true,
      isNewProduct: true,
      isAiRecommended: true,
      skinTypes: ['oily', 'normal', 'combination'],
      concerns: ['back-acne', 'rough-skin'],
      benefits: ['Clears back acne breakouts', 'Smooths rough KP bumps'],
      usage: ['Lather over body during shower.'],
      keyFacts: ['5% Lactic Acid', 'KP Treatment'],
      tags: ['aha-body-wash', 'bacne'],
      images: [{ url: '/images/products/bareo-oat-body-wash.png', alt: 'Bareo AHA Body Wash' }],
      status: 'active',
    },
    {
      sku: 'BAR-BC-005',
      slug: 'bareo-hydrating-coconut-squalane-body-oil',
      name: 'Bareo Hydrating Coconut & Squalane Body Oil',
      brand: 'Bareo',
      categoryId: categories[2]._id.toString(),
      categoryName: categories[2].name,
      categorySlug: categories[2].slug,
      shortDescription: 'Fast-absorbing glowing body oil with Coconut & Squalane',
      description: 'Bareo Body Oil leaves skin with a glossy summer sheen while nourishing deep epidermal layers. Dry oil texture absorbs quickly.',
      mrp: 449, offerPrice: 349, discount: 22,
      rating: 4.7,
      ratingCount: 95,
      stock: 75,
      isBestSeller: false,
      isTrending: true,
      isDoctorRecommended: false,
      isNewProduct: false,
      isAiRecommended: false,
      skinTypes: ['dry', 'normal'],
      concerns: ['dryness', 'dullness'],
      benefits: ['Gives radiant body sheen', 'Fast absorbing dry-oil texture'],
      usage: ['Smooth onto damp body after bath.'],
      keyFacts: ['Dry Oil', 'Squalane Infused'],
      tags: ['body-oil', 'squalane'],
      images: [{ url: '/images/products/bareo-shea-body-lotion.png', alt: 'Bareo Body Oil' }],
      status: 'active',
    },
    {
      sku: 'BAR-BC-006',
      slug: 'bareo-ultra-healing-hand-cream',
      name: 'Bareo Ultra-Healing Hand & Cuticle Cream',
      brand: 'Bareo',
      categoryId: categories[2]._id.toString(),
      categoryName: categories[2].name,
      categorySlug: categories[2].slug,
      shortDescription: 'Nourishing hand salve with Almond Oil & Beeswax',
      description: 'Repair overworked, dry hands and cracked cuticles with Bareo Hand Cream. Forms an invisible protective glove against frequent handwashing dryness.',
      mrp: 399, offerPrice: 299, discount: 25,
      rating: 4.9,
      ratingCount: 135,
      stock: 120,
      isBestSeller: false,
      isTrending: false,
      isDoctorRecommended: true,
      isNewProduct: false,
      isAiRecommended: false,
      skinTypes: ['dry', 'sensitive', 'normal'],
      concerns: ['dry-hands', 'cracked-skin'],
      benefits: ['Repairs cracked dry hands', 'Protects cuticles'],
      usage: ['Apply generously to hands as needed.'],
      keyFacts: ['Barrier Defense', 'Almond Oil'],
      tags: ['hand-cream', 'cuticles'],
      images: [{ url: '/images/products/bareo-shea-body-lotion.png', alt: 'Bareo Hand Cream' }],
      status: 'active',
    },
    {
      sku: 'BAR-BC-007',
      slug: 'bareo-smoothing-heel-repair-balm',
      name: 'Bareo Smoothing Heel Repair Balm',
      brand: 'Bareo',
      categoryId: categories[2]._id.toString(),
      categoryName: categories[2].name,
      categorySlug: categories[2].slug,
      shortDescription: 'Intense crack repair balm with 10% Urea & Salicylic Acid',
      description: 'Visibly heal cracked heels in 3 days with Bareo Heel Repair Balm. 10% Urea dissolves thick calluses while Kokum Butter softens cracks.',
      mrp: 399, offerPrice: 299, discount: 25,
      rating: 4.8,
      ratingCount: 160,
      stock: 100,
      isBestSeller: true,
      isTrending: false,
      isDoctorRecommended: true,
      isNewProduct: false,
      isAiRecommended: true,
      skinTypes: ['all'],
      concerns: ['cracked-heels', 'calluses'],
      benefits: ['Heals cracked heels in 3 days', 'Softens tough calluses'],
      usage: ['Apply on clean feet before bed.'],
      keyFacts: ['10% Urea', 'Fast Action'],
      tags: ['heel-balm', 'urea'],
      images: [{ url: '/images/products/bareo-shea-body-lotion.png', alt: 'Bareo Heel Balm' }],
      status: 'active',
    },

    // --- CATEGORY 4: Baby Care (6 Products - All Mapped to bareo-cica-serum.png) ---
    {
      sku: 'BAR-BB-001',
      slug: 'bareo-gentle-tear-free-baby-wash',
      name: 'Bareo Gentle Tear-Free Baby Head-to-Toe Wash',
      brand: 'Bareo',
      categoryId: categories[3]._id.toString(),
      categoryName: categories[3].name,
      categorySlug: categories[3].slug,
      shortDescription: 'Pediatrician certified tear-free wash with Chamomile & Calendula',
      description: 'Ultra-mild, tear-free cleansing for baby delicate hair and skin. Formulated with organic Chamomile and Aloe Vera to prevent dryness.',
      mrp: 299, offerPrice: 219, discount: 27,
      rating: 4.9,
      ratingCount: 180,
      stock: 130,
      isBestSeller: true,
      isTrending: true,
      isDoctorRecommended: true,
      isNewProduct: false,
      isAiRecommended: true,
      skinTypes: ['sensitive', 'baby'],
      concerns: ['baby-care', 'sensitivity'],
      benefits: ['100% Tear-Free certified', 'Hypoallergenic pH neutral'],
      usage: ['Wash baby hair and body gently.'],
      keyFacts: ['Pediatrician Approved', 'Tear-Free'],
      tags: ['baby-wash', 'chamomile'],
      images: [{ url: '/images/products/bareo-cica-serum.png', alt: 'Bareo Baby Wash' }],
      status: 'active',
    },
    {
      sku: 'BAR-BB-002',
      slug: 'bareo-oat-chamomile-calming-baby-lotion',
      name: 'Bareo Oat & Chamomile Ultra-Calming Baby Lotion',
      brand: 'Bareo',
      categoryId: categories[3]._id.toString(),
      categoryName: categories[3].name,
      categorySlug: categories[3].slug,
      shortDescription: 'Nourishing daily lotion with Colloidal Oat & Sweet Almond Oil',
      description: 'Keep baby skin soft, hydrated, and protected against dryness. Bareo Baby Lotion absorbs quickly without sticky residue.',
      mrp: 299, offerPrice: 229, discount: 23,
      rating: 4.9,
      ratingCount: 145,
      stock: 110,
      isBestSeller: true,
      isTrending: false,
      isDoctorRecommended: true,
      isNewProduct: false,
      isAiRecommended: true,
      skinTypes: ['sensitive', 'baby'],
      concerns: ['baby-care', 'dryness'],
      benefits: ['24-hour baby skin moisture', 'Soothes dry patches'],
      usage: ['Massage gently over baby body after bath.'],
      keyFacts: ['Hypoallergenic', 'Dermatologist Tested'],
      tags: ['baby-lotion', 'oatmeal'],
      images: [{ url: '/images/products/bareo-cica-serum.png', alt: 'Bareo Baby Lotion' }],
      status: 'active',
    },
    {
      sku: 'BAR-BB-003',
      slug: 'bareo-zinc-oxide-diaper-rash-cream',
      name: 'Bareo Zinc Oxide Protective Diaper Rash Cream',
      brand: 'Bareo',
      categoryId: categories[3]._id.toString(),
      categoryName: categories[3].name,
      categorySlug: categories[3].slug,
      shortDescription: 'Rapid relief rash barrier cream with 15% Zinc Oxide & Shea Butter',
      description: 'Form a breathable waterproof shield against wetness and diaper friction. Bareo Diaper Cream calms redness and heals rashes fast.',
      mrp: 399, offerPrice: 299, discount: 25,
      rating: 4.9,
      ratingCount: 220,
      stock: 125,
      isBestSeller: true,
      isTrending: true,
      isDoctorRecommended: true,
      isNewProduct: false,
      isAiRecommended: true,
      skinTypes: ['sensitive', 'baby'],
      concerns: ['diaper-rash', 'redness'],
      benefits: ['Relieves diaper rash instantly', 'Forms waterproof shield'],
      usage: ['Apply thick layer at every diaper change.'],
      keyFacts: ['15% Zinc Oxide', 'Pediatrician Recommended'],
      tags: ['rash-cream', 'zinc-oxide'],
      images: [{ url: '/images/products/bareo-cica-serum.png', alt: 'Bareo Diaper Rash Cream' }],
      status: 'active',
    },
    {
      sku: 'BAR-BB-004',
      slug: 'bareo-sweet-almond-baby-massage-oil',
      name: 'Bareo Cold-Pressed Sweet Almond Baby Massage Oil',
      brand: 'Bareo',
      categoryId: categories[3]._id.toString(),
      categoryName: categories[3].name,
      categorySlug: categories[3].slug,
      shortDescription: '100% pure cold-pressed almond oil for daily baby massage',
      description: 'Strengthen baby bones and nourish skin with Bareo Cold-Pressed Almond Oil. Unrefined, light, and 100% edible-grade pure oil.',
      mrp: 449, offerPrice: 349, discount: 22,
      rating: 4.8,
      ratingCount: 160,
      stock: 90,
      isBestSeller: false,
      isTrending: true,
      isDoctorRecommended: true,
      isNewProduct: false,
      isAiRecommended: false,
      skinTypes: ['sensitive', 'baby'],
      concerns: ['baby-care', 'dryness'],
      benefits: ['Nourishes baby bones and skin', '100% pure cold pressed'],
      usage: ['Warm small amount on palms and massage baby.'],
      keyFacts: ['100% Pure Almond', 'No Mineral Oil'],
      tags: ['massage-oil', 'almond-oil'],
      images: [{ url: '/images/products/bareo-cica-serum.png', alt: 'Bareo Baby Massage Oil' }],
      status: 'active',
    },
    {
      sku: 'BAR-BB-005',
      slug: 'bareo-hydrating-baby-face-body-butter',
      name: 'Bareo Hydrating Baby Face & Body Butter',
      brand: 'Bareo',
      categoryId: categories[3]._id.toString(),
      categoryName: categories[3].name,
      categorySlug: categories[3].slug,
      shortDescription: 'Ultra-nourishing face balm with Mango Butter & Aloe Vera',
      description: 'Protect baby cheeks against cold wind drying and drool rash with Bareo Baby Face Butter. Rich soothing balm texture.',
      mrp: 299, offerPrice: 229, discount: 23,
      rating: 4.7,
      ratingCount: 90,
      stock: 80,
      isBestSeller: false,
      isTrending: false,
      isDoctorRecommended: false,
      isNewProduct: true,
      isAiRecommended: false,
      skinTypes: ['sensitive', 'baby'],
      concerns: ['drool-rash', 'dry-cheeks'],
      benefits: ['Protects cheeks from drool rash', 'Soothing rich balm'],
      usage: ['Dab gently onto baby cheeks and chin.'],
      keyFacts: ['Pediatrician Tested', 'Mango Butter'],
      tags: ['baby-butter', 'drool-rash'],
      images: [{ url: '/images/products/bareo-cica-serum.png', alt: 'Bareo Baby Face Butter' }],
      status: 'active',
    },
    {
      sku: 'BAR-BB-006',
      slug: 'bareo-talc-free-botanical-baby-powder',
      name: 'Bareo Soothing Botanical Baby Powder (Talc-Free)',
      brand: 'Bareo',
      categoryId: categories[3]._id.toString(),
      categoryName: categories[3].name,
      categorySlug: categories[3].slug,
      shortDescription: '100% Talc-Free dusting powder with Arrowroot & Lavender',
      description: 'Keep baby skin folds fresh and dry naturally. 100% Talc-Free cornstarch and arrowroot powder absorbs excess dampness without clogging pores.',
      mrp: 299, offerPrice: 229, discount: 23,
      rating: 4.9,
      ratingCount: 170,
      stock: 110,
      isBestSeller: true,
      isTrending: true,
      isDoctorRecommended: true,
      isNewProduct: false,
      isAiRecommended: true,
      skinTypes: ['sensitive', 'baby'],
      concerns: ['sweat-folds', 'chafing'],
      benefits: ['100% Talc-Free safe formula', 'Absorbs moisture in skin folds'],
      usage: ['Dust onto hands then pat gently on baby skin folds.'],
      keyFacts: ['100% Talc-Free', 'Cornstarch & Arrowroot'],
      tags: ['baby-powder', 'talc-free'],
      images: [{ url: '/images/products/bareo-cica-serum.png', alt: 'Bareo Baby Powder' }],
      status: 'active',
    },
  ])

  console.log('✅ Bareo Database Seed Complete with all 28 Products! Ready for RC Release.')
  await mongoose.disconnect()
}

seed().catch((err) => {
  console.error('❌ Seeding Failed:', err)
  process.exit(1)
})
